// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/client_abr_state.proto
// Protobuf C++ Version: 6.33.4

#include "video_streaming/client_abr_state.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace video_streaming {

inline constexpr ClientAbrState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sabr_license_constraint_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        time_since_last_manual_format_selection_ms_{::int64_t{0}},
        last_manual_direction_{0},
        last_manual_selected_resolution_{0},
        detailed_network_type_{0},
        client_viewport_width_{0},
        client_bitrate_cap_bytes_per_sec_{::int64_t{0}},
        client_viewport_height_{0},
        sticky_resolution_{0},
        bandwidth_estimate_{::int64_t{0}},
        min_audio_quality_{static_cast< ::misc::AudioQuality >(0)},
        max_audio_quality_{static_cast< ::misc::AudioQuality >(0)},
        video_quality_setting_{static_cast< ::misc::VideoQualitySetting >(0)},
        client_viewport_is_flexible_{false},
        data_saver_mode_{false},
        player_time_ms_{::int64_t{0}},
        time_since_last_seek_{::int64_t{0}},
        audio_route_{static_cast< ::misc::PlaybackAudioRouteOutputType >(0)},
        audio_track_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        media_capabilities_{nullptr},
        playback_authorization_{nullptr},
        network_metered_state_{static_cast< ::misc::NetworkMeteredState >(0)},
        visibility_{0},
        elapsed_wall_time_ms_{::int64_t{0}},
        playback_rate_{0},
        enabled_track_types_bitfield_{0},
        time_since_last_action_ms_{::int64_t{0}},
        player_state_{::int64_t{0}},
        max_pacing_rate_{0},
        field48_{0},
        field50_{0},
        field51_{0},
        sabr_report_request_cancellation_info_{0},
        drc_enabled_{false},
        disable_streaming_xhr_{false},
        prefer_vp9_{false},
        is_prefetch_{false},
        field57_{::int64_t{0}},
        av1_quality_threshold_{0},
        field60_{0},
        allow_proxima_live_latency_{0},
        sabr_force_proxima_{0},
        sabr_force_max_network_interruption_duration_ms_{::int64_t{0}},
        field67_{0},
        sabr_support_quality_constraints_{false},
        enable_voice_boost_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ClientAbrState::ClientAbrState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ClientAbrState_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClientAbrStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClientAbrStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClientAbrStateDefaultTypeInternal() {}
  union {
    ClientAbrState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClientAbrStateDefaultTypeInternal _ClientAbrState_default_instance_;
}  // namespace video_streaming
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_video_5fstreaming_2fclient_5fabr_5fstate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_video_5fstreaming_2fclient_5fabr_5fstate_2eproto = nullptr;
const ::uint32_t
    TableStruct_video_5fstreaming_2fclient_5fabr_5fstate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_._has_bits_),
        49, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.time_since_last_manual_format_selection_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.last_manual_direction_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.last_manual_selected_resolution_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.detailed_network_type_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.client_viewport_width_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.client_viewport_height_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.client_bitrate_cap_bytes_per_sec_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.sticky_resolution_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.client_viewport_is_flexible_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.bandwidth_estimate_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.min_audio_quality_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.max_audio_quality_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.video_quality_setting_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.audio_route_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.player_time_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.time_since_last_seek_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.data_saver_mode_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.network_metered_state_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.visibility_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.playback_rate_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.elapsed_wall_time_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.media_capabilities_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.time_since_last_action_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.enabled_track_types_bitfield_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.max_pacing_rate_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.player_state_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.drc_enabled_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.field48_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.field50_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.field51_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.sabr_report_request_cancellation_info_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.disable_streaming_xhr_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.field57_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.prefer_vp9_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.av1_quality_threshold_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.field60_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.is_prefetch_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.sabr_support_quality_constraints_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.sabr_license_constraint_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.allow_proxima_live_latency_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.sabr_force_proxima_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.field67_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.sabr_force_max_network_interruption_duration_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.audio_track_id_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.enable_voice_boost_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::ClientAbrState, _impl_.playback_authorization_),
        1,
        2,
        3,
        4,
        5,
        7,
        6,
        8,
        13,
        9,
        10,
        11,
        12,
        17,
        15,
        16,
        14,
        21,
        22,
        24,
        23,
        19,
        26,
        25,
        28,
        27,
        33,
        29,
        30,
        31,
        32,
        34,
        37,
        35,
        38,
        39,
        36,
        44,
        0,
        40,
        41,
        43,
        42,
        18,
        45,
        20,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::video_streaming::ClientAbrState)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::video_streaming::_ClientAbrState_default_instance_._instance,
};
const char descriptor_table_protodef_video_5fstreaming_2fclient_5fabr_5fstate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n&video_streaming/client_abr_state.proto"
    "\022\017video_streaming\032\021misc/common.proto\032(vi"
    "deo_streaming/media_capabilities.proto\"\221"
    "\014\n\016ClientAbrState\0222\n*time_since_last_man"
    "ual_format_selection_ms\030\r \001(\003\022\035\n\025last_ma"
    "nual_direction\030\016 \001(\021\022\'\n\037last_manual_sele"
    "cted_resolution\030\020 \001(\005\022\035\n\025detailed_networ"
    "k_type\030\021 \001(\005\022\035\n\025client_viewport_width\030\022 "
    "\001(\005\022\036\n\026client_viewport_height\030\023 \001(\005\022(\n c"
    "lient_bitrate_cap_bytes_per_sec\030\024 \001(\003\022\031\n"
    "\021sticky_resolution\030\025 \001(\005\022#\n\033client_viewp"
    "ort_is_flexible\030\026 \001(\010\022\032\n\022bandwidth_estim"
    "ate\030\027 \001(\003\022-\n\021min_audio_quality\030\030 \001(\0162\022.m"
    "isc.AudioQuality\022-\n\021max_audio_quality\030\031 "
    "\001(\0162\022.misc.AudioQuality\0228\n\025video_quality"
    "_setting\030\032 \001(\0162\031.misc.VideoQualitySettin"
    "g\0227\n\013audio_route\030\033 \001(\0162\".misc.PlaybackAu"
    "dioRouteOutputType\022\026\n\016player_time_ms\030\034 \001"
    "(\003\022\034\n\024time_since_last_seek\030\035 \001(\003\022\027\n\017data"
    "_saver_mode\030\036 \001(\010\0228\n\025network_metered_sta"
    "te\030  \001(\0162\031.misc.NetworkMeteredState\022\022\n\nv"
    "isibility\030\" \001(\005\022\025\n\rplayback_rate\030# \001(\002\022\034"
    "\n\024elapsed_wall_time_ms\030$ \001(\003\022>\n\022media_ca"
    "pabilities\030& \001(\0132\".video_streaming.Media"
    "Capabilities\022!\n\031time_since_last_action_m"
    "s\030\' \001(\003\022$\n\034enabled_track_types_bitfield\030"
    "( \001(\005\022\027\n\017max_pacing_rate\030+ \001(\005\022\024\n\014player"
    "_state\030, \001(\003\022\023\n\013drc_enabled\030. \001(\010\022\017\n\007fie"
    "ld48\0300 \001(\005\022\017\n\007field50\0302 \001(\005\022\017\n\007field51\0303"
    " \001(\005\022-\n%sabr_report_request_cancellation"
    "_info\0306 \001(\005\022\035\n\025disable_streaming_xhr\0308 \001"
    "(\010\022\017\n\007field57\0309 \001(\003\022\022\n\nprefer_vp9\030: \001(\010\022"
    "\035\n\025av1_quality_threshold\030; \001(\005\022\017\n\007field6"
    "0\030< \001(\005\022\023\n\013is_prefetch\030= \001(\010\022(\n sabr_sup"
    "port_quality_constraints\030> \001(\010\022\037\n\027sabr_l"
    "icense_constraint\030\? \001(\014\022\"\n\032allow_proxima"
    "_live_latency\030@ \001(\005\022\032\n\022sabr_force_proxim"
    "a\030B \001(\005\022\017\n\007field67\030C \001(\005\0227\n/sabr_force_m"
    "ax_network_interruption_duration_ms\030D \001("
    "\003\022\026\n\016audio_track_id\030E \001(\t\022\032\n\022enable_voic"
    "e_boost\030L \001(\010\022;\n\026playback_authorization\030"
    "O \001(\0132\033.misc.PlaybackAuthorization"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto_deps[2] = {
        &::descriptor_table_misc_2fcommon_2eproto,
        &::descriptor_table_video_5fstreaming_2fmedia_5fcapabilities_2eproto,
};
static ::absl::once_flag descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto = {
    false,
    false,
    1674,
    descriptor_table_protodef_video_5fstreaming_2fclient_5fabr_5fstate_2eproto,
    "video_streaming/client_abr_state.proto",
    &descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto_once,
    descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_video_5fstreaming_2fclient_5fabr_5fstate_2eproto::offsets,
    file_level_enum_descriptors_video_5fstreaming_2fclient_5fabr_5fstate_2eproto,
    file_level_service_descriptors_video_5fstreaming_2fclient_5fabr_5fstate_2eproto,
};
namespace video_streaming {
// ===================================================================

class ClientAbrState::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ClientAbrState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_._has_bits_);
};

void ClientAbrState::clear_media_capabilities() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.media_capabilities_ != nullptr) _impl_.media_capabilities_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00080000U);
}
void ClientAbrState::clear_playback_authorization() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playback_authorization_ != nullptr) _impl_.playback_authorization_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00100000U);
}
ClientAbrState::ClientAbrState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ClientAbrState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.ClientAbrState)
}
PROTOBUF_NDEBUG_INLINE ClientAbrState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::ClientAbrState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sabr_license_constraint_(arena, from.sabr_license_constraint_),
        audio_track_id_(arena, from.audio_track_id_) {}

ClientAbrState::ClientAbrState(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ClientAbrState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ClientAbrState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClientAbrState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_since_last_manual_format_selection_ms_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, time_since_last_manual_format_selection_ms_),
           offsetof(Impl_, audio_route_) -
               offsetof(Impl_, time_since_last_manual_format_selection_ms_) +
               sizeof(Impl_::audio_route_));
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.media_capabilities_ = (CheckHasBit(cached_has_bits, 0x00080000U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.media_capabilities_)
                : nullptr;
  _impl_.playback_authorization_ = (CheckHasBit(cached_has_bits, 0x00100000U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.playback_authorization_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, network_metered_state_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, network_metered_state_),
           offsetof(Impl_, enable_voice_boost_) -
               offsetof(Impl_, network_metered_state_) +
               sizeof(Impl_::enable_voice_boost_));

  // @@protoc_insertion_point(copy_constructor:video_streaming.ClientAbrState)
}
PROTOBUF_NDEBUG_INLINE ClientAbrState::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        sabr_license_constraint_(arena),
        audio_track_id_(arena) {}

inline void ClientAbrState::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_since_last_manual_format_selection_ms_),
           0,
           offsetof(Impl_, audio_route_) -
               offsetof(Impl_, time_since_last_manual_format_selection_ms_) +
               sizeof(Impl_::audio_route_));
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, media_capabilities_),
           0,
           offsetof(Impl_, enable_voice_boost_) -
               offsetof(Impl_, media_capabilities_) +
               sizeof(Impl_::enable_voice_boost_));
}
ClientAbrState::~ClientAbrState() {
  // @@protoc_insertion_point(destructor:video_streaming.ClientAbrState)
  SharedDtor(*this);
}
inline void ClientAbrState::SharedDtor(MessageLite& self) {
  ClientAbrState& this_ = static_cast<ClientAbrState&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sabr_license_constraint_.Destroy();
  this_._impl_.audio_track_id_.Destroy();
  delete this_._impl_.media_capabilities_;
  delete this_._impl_.playback_authorization_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ClientAbrState::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ClientAbrState(arena);
}
constexpr auto ClientAbrState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ClientAbrState),
                                            alignof(ClientAbrState));
}
constexpr auto ClientAbrState::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ClientAbrState_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ClientAbrState::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ClientAbrState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ClientAbrState::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ClientAbrState>(), &ClientAbrState::ByteSizeLong,
              &ClientAbrState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_._cached_size_),
          false,
      },
      &ClientAbrState::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ClientAbrState_class_data_ =
        ClientAbrState::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ClientAbrState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ClientAbrState_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ClientAbrState_class_data_.tc_table);
  return ClientAbrState_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 46, 7, 0, 11>
ClientAbrState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_._has_bits_),
    0, // no _extensions_
    79, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    1073762303,  // skipmap
    offsetof(decltype(_table_), field_entries),
    46,  // num_field_entries
    7,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ClientAbrState_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::ClientAbrState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional int64 time_since_last_manual_format_selection_ms = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ClientAbrState, _impl_.time_since_last_manual_format_selection_ms_), 1>(),
     {104, 1, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.time_since_last_manual_format_selection_ms_)}},
    // optional sint32 last_manual_direction = 14;
    {::_pbi::TcParser::FastZ32S1,
     {112, 2, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.last_manual_direction_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 last_manual_selected_resolution = 16;
    {::_pbi::TcParser::FastV32S2,
     {384, 3, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.last_manual_selected_resolution_)}},
    // optional int32 detailed_network_type = 17;
    {::_pbi::TcParser::FastV32S2,
     {392, 4, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.detailed_network_type_)}},
    // optional int32 client_viewport_width = 18;
    {::_pbi::TcParser::FastV32S2,
     {400, 5, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_viewport_width_)}},
    // optional int32 client_viewport_height = 19;
    {::_pbi::TcParser::FastV32S2,
     {408, 7, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_viewport_height_)}},
    // optional int64 client_bitrate_cap_bytes_per_sec = 20;
    {::_pbi::TcParser::FastV64S2,
     {416, 6, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_bitrate_cap_bytes_per_sec_)}},
    // optional int32 sticky_resolution = 21;
    {::_pbi::TcParser::FastV32S2,
     {424, 8, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sticky_resolution_)}},
    // optional bool client_viewport_is_flexible = 22;
    {::_pbi::TcParser::FastV8S2,
     {432, 13, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_viewport_is_flexible_)}},
    // optional int64 bandwidth_estimate = 23;
    {::_pbi::TcParser::FastV64S2,
     {440, 9, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.bandwidth_estimate_)}},
    // optional .misc.AudioQuality min_audio_quality = 24;
    {::_pbi::TcParser::FastEvS2,
     {448, 10, 2,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.min_audio_quality_)}},
    // optional .misc.AudioQuality max_audio_quality = 25;
    {::_pbi::TcParser::FastEvS2,
     {456, 11, 3,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.max_audio_quality_)}},
    // optional .misc.VideoQualitySetting video_quality_setting = 26;
    {::_pbi::TcParser::FastEr0S2,
     {464, 12, 3,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.video_quality_setting_)}},
    // optional .misc.PlaybackAudioRouteOutputType audio_route = 27;
    {::_pbi::TcParser::FastEr0S2,
     {472, 17, 12,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.audio_route_)}},
    // optional int64 player_time_ms = 28;
    {::_pbi::TcParser::FastV64S2,
     {480, 15, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.player_time_ms_)}},
    // optional int64 time_since_last_seek = 29;
    {::_pbi::TcParser::FastV64S2,
     {488, 16, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.time_since_last_seek_)}},
    // optional bool data_saver_mode = 30;
    {::_pbi::TcParser::FastV8S2,
     {496, 14, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.data_saver_mode_)}},
    // optional bytes sabr_license_constraint = 63;
    {::_pbi::TcParser::FastBS2,
     {1018, 0, 0,
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sabr_license_constraint_)}},
  }}, {{
    34, 0, 3,
    43400, 18,
    32812, 28,
    56304, 40,
    65535, 65535
  }}, {{
    // optional int64 time_since_last_manual_format_selection_ms = 13;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.time_since_last_manual_format_selection_ms_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional sint32 last_manual_direction = 14;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.last_manual_direction_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt32)},
    // optional int32 last_manual_selected_resolution = 16;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.last_manual_selected_resolution_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 detailed_network_type = 17;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.detailed_network_type_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 client_viewport_width = 18;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_viewport_width_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 client_viewport_height = 19;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_viewport_height_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 client_bitrate_cap_bytes_per_sec = 20;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_bitrate_cap_bytes_per_sec_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int32 sticky_resolution = 21;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sticky_resolution_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bool client_viewport_is_flexible = 22;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.client_viewport_is_flexible_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int64 bandwidth_estimate = 23;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.bandwidth_estimate_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .misc.AudioQuality min_audio_quality = 24;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.min_audio_quality_), _Internal::kHasBitsOffset + 10, 2, (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional .misc.AudioQuality max_audio_quality = 25;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.max_audio_quality_), _Internal::kHasBitsOffset + 11, 3, (0 | ::_fl::kFcOptional | ::_fl::kEnum)},
    // optional .misc.VideoQualitySetting video_quality_setting = 26;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.video_quality_setting_), _Internal::kHasBitsOffset + 12, 4, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional .misc.PlaybackAudioRouteOutputType audio_route = 27;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.audio_route_), _Internal::kHasBitsOffset + 17, 5, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional int64 player_time_ms = 28;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.player_time_ms_), _Internal::kHasBitsOffset + 15, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 time_since_last_seek = 29;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.time_since_last_seek_), _Internal::kHasBitsOffset + 16, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional bool data_saver_mode = 30;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.data_saver_mode_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .misc.NetworkMeteredState network_metered_state = 32;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.network_metered_state_), _Internal::kHasBitsOffset + 21, 6, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional int32 visibility = 34;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.visibility_), _Internal::kHasBitsOffset + 22, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional float playback_rate = 35;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.playback_rate_), _Internal::kHasBitsOffset + 24, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional int64 elapsed_wall_time_ms = 36;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.elapsed_wall_time_ms_), _Internal::kHasBitsOffset + 23, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .video_streaming.MediaCapabilities media_capabilities = 38;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.media_capabilities_), _Internal::kHasBitsOffset + 19, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int64 time_since_last_action_ms = 39;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.time_since_last_action_ms_), _Internal::kHasBitsOffset + 26, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int32 enabled_track_types_bitfield = 40;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.enabled_track_types_bitfield_), _Internal::kHasBitsOffset + 25, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 max_pacing_rate = 43;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.max_pacing_rate_), _Internal::kHasBitsOffset + 28, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 player_state = 44;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.player_state_), _Internal::kHasBitsOffset + 27, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional bool drc_enabled = 46;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.drc_enabled_), _Internal::kHasBitsOffset + 33, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 field48 = 48;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.field48_), _Internal::kHasBitsOffset + 29, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 field50 = 50;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.field50_), _Internal::kHasBitsOffset + 30, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 field51 = 51;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.field51_), _Internal::kHasBitsOffset + 31, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 sabr_report_request_cancellation_info = 54;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sabr_report_request_cancellation_info_), _Internal::kHasBitsOffset + 32, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bool disable_streaming_xhr = 56;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.disable_streaming_xhr_), _Internal::kHasBitsOffset + 34, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int64 field57 = 57;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.field57_), _Internal::kHasBitsOffset + 37, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional bool prefer_vp9 = 58;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.prefer_vp9_), _Internal::kHasBitsOffset + 35, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 av1_quality_threshold = 59;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.av1_quality_threshold_), _Internal::kHasBitsOffset + 38, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 field60 = 60;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.field60_), _Internal::kHasBitsOffset + 39, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bool is_prefetch = 61;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.is_prefetch_), _Internal::kHasBitsOffset + 36, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool sabr_support_quality_constraints = 62;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sabr_support_quality_constraints_), _Internal::kHasBitsOffset + 44, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bytes sabr_license_constraint = 63;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sabr_license_constraint_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 allow_proxima_live_latency = 64;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.allow_proxima_live_latency_), _Internal::kHasBitsOffset + 40, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 sabr_force_proxima = 66;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sabr_force_proxima_), _Internal::kHasBitsOffset + 41, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 field67 = 67;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.field67_), _Internal::kHasBitsOffset + 43, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 sabr_force_max_network_interruption_duration_ms = 68;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.sabr_force_max_network_interruption_duration_ms_), _Internal::kHasBitsOffset + 42, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional string audio_track_id = 69;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.audio_track_id_), _Internal::kHasBitsOffset + 18, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bool enable_voice_boost = 76;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.enable_voice_boost_), _Internal::kHasBitsOffset + 45, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .misc.PlaybackAuthorization playback_authorization = 79;
    {PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.playback_authorization_), _Internal::kHasBitsOffset + 20, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::video_streaming::MediaCapabilities>()},
      {::_pbi::TcParser::GetTable<::misc::PlaybackAuthorization>()},
      {::_pbi::FieldAuxEnumData{}, ::misc::AudioQuality_internal_data_},
      {::_pbi::FieldAuxEnumData{}, ::misc::AudioQuality_internal_data_},
      {0, 3},
      {0, 12},
      {0, 2},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ClientAbrState::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.ClientAbrState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.sabr_license_constraint_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000feU)) {
    ::memset(&_impl_.time_since_last_manual_format_selection_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.client_viewport_height_) -
        reinterpret_cast<char*>(&_impl_.time_since_last_manual_format_selection_ms_)) + sizeof(_impl_.client_viewport_height_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    ::memset(&_impl_.sticky_resolution_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.player_time_ms_) -
        reinterpret_cast<char*>(&_impl_.sticky_resolution_)) + sizeof(_impl_.player_time_ms_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x001f0000U)) {
    ::memset(&_impl_.time_since_last_seek_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.audio_route_) -
        reinterpret_cast<char*>(&_impl_.time_since_last_seek_)) + sizeof(_impl_.audio_route_));
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      _impl_.audio_track_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      ABSL_DCHECK(_impl_.media_capabilities_ != nullptr);
      _impl_.media_capabilities_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00100000U)) {
      ABSL_DCHECK(_impl_.playback_authorization_ != nullptr);
      _impl_.playback_authorization_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00e00000U)) {
    ::memset(&_impl_.network_metered_state_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.elapsed_wall_time_ms_) -
        reinterpret_cast<char*>(&_impl_.network_metered_state_)) + sizeof(_impl_.elapsed_wall_time_ms_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0xff000000U)) {
    ::memset(&_impl_.playback_rate_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.field51_) -
        reinterpret_cast<char*>(&_impl_.playback_rate_)) + sizeof(_impl_.field51_));
  }
  cached_has_bits = _impl_._has_bits_[1];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    ::memset(&_impl_.sabr_report_request_cancellation_info_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.field60_) -
        reinterpret_cast<char*>(&_impl_.sabr_report_request_cancellation_info_)) + sizeof(_impl_.field60_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00003f00U)) {
    ::memset(&_impl_.allow_proxima_live_latency_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.enable_voice_boost_) -
        reinterpret_cast<char*>(&_impl_.allow_proxima_live_latency_)) + sizeof(_impl_.enable_voice_boost_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ClientAbrState::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ClientAbrState& this_ = static_cast<const ClientAbrState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ClientAbrState::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ClientAbrState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.ClientAbrState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 time_since_last_manual_format_selection_ms = 13;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<13>(
            stream, this_._internal_time_since_last_manual_format_selection_ms(), target);
  }

  // optional sint32 last_manual_direction = 14;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        14, this_._internal_last_manual_direction(), target);
  }

  // optional int32 last_manual_selected_resolution = 16;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        16, this_._internal_last_manual_selected_resolution(), target);
  }

  // optional int32 detailed_network_type = 17;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        17, this_._internal_detailed_network_type(), target);
  }

  // optional int32 client_viewport_width = 18;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        18, this_._internal_client_viewport_width(), target);
  }

  // optional int32 client_viewport_height = 19;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        19, this_._internal_client_viewport_height(), target);
  }

  // optional int64 client_bitrate_cap_bytes_per_sec = 20;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        20, this_._internal_client_bitrate_cap_bytes_per_sec(), target);
  }

  // optional int32 sticky_resolution = 21;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        21, this_._internal_sticky_resolution(), target);
  }

  // optional bool client_viewport_is_flexible = 22;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        22, this_._internal_client_viewport_is_flexible(), target);
  }

  // optional int64 bandwidth_estimate = 23;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        23, this_._internal_bandwidth_estimate(), target);
  }

  // optional .misc.AudioQuality min_audio_quality = 24;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        24, this_._internal_min_audio_quality(), target);
  }

  // optional .misc.AudioQuality max_audio_quality = 25;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        25, this_._internal_max_audio_quality(), target);
  }

  // optional .misc.VideoQualitySetting video_quality_setting = 26;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        26, this_._internal_video_quality_setting(), target);
  }

  // optional .misc.PlaybackAudioRouteOutputType audio_route = 27;
  if (CheckHasBit(cached_has_bits, 0x00020000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        27, this_._internal_audio_route(), target);
  }

  // optional int64 player_time_ms = 28;
  if (CheckHasBit(cached_has_bits, 0x00008000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        28, this_._internal_player_time_ms(), target);
  }

  // optional int64 time_since_last_seek = 29;
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        29, this_._internal_time_since_last_seek(), target);
  }

  // optional bool data_saver_mode = 30;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        30, this_._internal_data_saver_mode(), target);
  }

  // optional .misc.NetworkMeteredState network_metered_state = 32;
  if (CheckHasBit(cached_has_bits, 0x00200000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        32, this_._internal_network_metered_state(), target);
  }

  // optional int32 visibility = 34;
  if (CheckHasBit(cached_has_bits, 0x00400000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        34, this_._internal_visibility(), target);
  }

  // optional float playback_rate = 35;
  if (CheckHasBit(cached_has_bits, 0x01000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        35, this_._internal_playback_rate(), target);
  }

  // optional int64 elapsed_wall_time_ms = 36;
  if (CheckHasBit(cached_has_bits, 0x00800000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        36, this_._internal_elapsed_wall_time_ms(), target);
  }

  // optional .video_streaming.MediaCapabilities media_capabilities = 38;
  if (CheckHasBit(cached_has_bits, 0x00080000U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        38, *this_._impl_.media_capabilities_, this_._impl_.media_capabilities_->GetCachedSize(), target,
        stream);
  }

  // optional int64 time_since_last_action_ms = 39;
  if (CheckHasBit(cached_has_bits, 0x04000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        39, this_._internal_time_since_last_action_ms(), target);
  }

  // optional int32 enabled_track_types_bitfield = 40;
  if (CheckHasBit(cached_has_bits, 0x02000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        40, this_._internal_enabled_track_types_bitfield(), target);
  }

  // optional int32 max_pacing_rate = 43;
  if (CheckHasBit(cached_has_bits, 0x10000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        43, this_._internal_max_pacing_rate(), target);
  }

  // optional int64 player_state = 44;
  if (CheckHasBit(cached_has_bits, 0x08000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        44, this_._internal_player_state(), target);
  }

  cached_has_bits = this_._impl_._has_bits_[1];
  // optional bool drc_enabled = 46;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        46, this_._internal_drc_enabled(), target);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 field48 = 48;
  if (CheckHasBit(cached_has_bits, 0x20000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        48, this_._internal_field48(), target);
  }

  // optional int32 field50 = 50;
  if (CheckHasBit(cached_has_bits, 0x40000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        50, this_._internal_field50(), target);
  }

  // optional int32 field51 = 51;
  if (CheckHasBit(cached_has_bits, 0x80000000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        51, this_._internal_field51(), target);
  }

  cached_has_bits = this_._impl_._has_bits_[1];
  // optional int32 sabr_report_request_cancellation_info = 54;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        54, this_._internal_sabr_report_request_cancellation_info(), target);
  }

  // optional bool disable_streaming_xhr = 56;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        56, this_._internal_disable_streaming_xhr(), target);
  }

  // optional int64 field57 = 57;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        57, this_._internal_field57(), target);
  }

  // optional bool prefer_vp9 = 58;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        58, this_._internal_prefer_vp9(), target);
  }

  // optional int32 av1_quality_threshold = 59;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        59, this_._internal_av1_quality_threshold(), target);
  }

  // optional int32 field60 = 60;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        60, this_._internal_field60(), target);
  }

  // optional bool is_prefetch = 61;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        61, this_._internal_is_prefetch(), target);
  }

  // optional bool sabr_support_quality_constraints = 62;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        62, this_._internal_sabr_support_quality_constraints(), target);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes sabr_license_constraint = 63;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_sabr_license_constraint();
    target = stream->WriteBytesMaybeAliased(63, _s, target);
  }

  cached_has_bits = this_._impl_._has_bits_[1];
  // optional int32 allow_proxima_live_latency = 64;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        64, this_._internal_allow_proxima_live_latency(), target);
  }

  // optional int32 sabr_force_proxima = 66;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        66, this_._internal_sabr_force_proxima(), target);
  }

  // optional int32 field67 = 67;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        67, this_._internal_field67(), target);
  }

  // optional int64 sabr_force_max_network_interruption_duration_ms = 68;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        68, this_._internal_sabr_force_max_network_interruption_duration_ms(), target);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string audio_track_id = 69;
  if (CheckHasBit(cached_has_bits, 0x00040000U)) {
    const ::std::string& _s = this_._internal_audio_track_id();
    target = stream->WriteStringMaybeAliased(69, _s, target);
  }

  cached_has_bits = this_._impl_._has_bits_[1];
  // optional bool enable_voice_boost = 76;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        76, this_._internal_enable_voice_boost(), target);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .misc.PlaybackAuthorization playback_authorization = 79;
  if (CheckHasBit(cached_has_bits, 0x00100000U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        79, *this_._impl_.playback_authorization_, this_._impl_.playback_authorization_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.ClientAbrState)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ClientAbrState::ByteSizeLong(const MessageLite& base) {
  const ClientAbrState& this_ = static_cast<const ClientAbrState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ClientAbrState::ByteSizeLong() const {
  const ClientAbrState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.ClientAbrState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x01000000U & cached_has_bits) * 6;
  total_size += ::absl::popcount(0x00006000U & cached_has_bits) * 3;
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // optional bytes sabr_license_constraint = 63;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_sabr_license_constraint());
    }
    // optional int64 time_since_last_manual_format_selection_ms = 13;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_time_since_last_manual_format_selection_ms());
    }
    // optional sint32 last_manual_direction = 14;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
          this_._internal_last_manual_direction());
    }
    // optional int32 last_manual_selected_resolution = 16;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_last_manual_selected_resolution());
    }
    // optional int32 detailed_network_type = 17;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_detailed_network_type());
    }
    // optional int32 client_viewport_width = 18;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_client_viewport_width());
    }
    // optional int64 client_bitrate_cap_bytes_per_sec = 20;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_client_bitrate_cap_bytes_per_sec());
    }
    // optional int32 client_viewport_height = 19;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_client_viewport_height());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00009f00U)) {
    // optional int32 sticky_resolution = 21;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_sticky_resolution());
    }
    // optional int64 bandwidth_estimate = 23;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_bandwidth_estimate());
    }
    // optional .misc.AudioQuality min_audio_quality = 24;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      total_size += 2 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_min_audio_quality());
    }
    // optional .misc.AudioQuality max_audio_quality = 25;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      total_size += 2 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_max_audio_quality());
    }
    // optional .misc.VideoQualitySetting video_quality_setting = 26;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      total_size += 2 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_video_quality_setting());
    }
    // optional int64 player_time_ms = 28;
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_player_time_ms());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00ff0000U)) {
    // optional int64 time_since_last_seek = 29;
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_time_since_last_seek());
    }
    // optional .misc.PlaybackAudioRouteOutputType audio_route = 27;
    if (CheckHasBit(cached_has_bits, 0x00020000U)) {
      total_size += 2 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_audio_route());
    }
    // optional string audio_track_id = 69;
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      total_size += 2 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_audio_track_id());
    }
    // optional .video_streaming.MediaCapabilities media_capabilities = 38;
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.media_capabilities_);
    }
    // optional .misc.PlaybackAuthorization playback_authorization = 79;
    if (CheckHasBit(cached_has_bits, 0x00100000U)) {
      total_size += 2 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.playback_authorization_);
    }
    // optional .misc.NetworkMeteredState network_metered_state = 32;
    if (CheckHasBit(cached_has_bits, 0x00200000U)) {
      total_size += 2 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_network_metered_state());
    }
    // optional int32 visibility = 34;
    if (CheckHasBit(cached_has_bits, 0x00400000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_visibility());
    }
    // optional int64 elapsed_wall_time_ms = 36;
    if (CheckHasBit(cached_has_bits, 0x00800000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_elapsed_wall_time_ms());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0xfe000000U)) {
    // optional int32 enabled_track_types_bitfield = 40;
    if (CheckHasBit(cached_has_bits, 0x02000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_enabled_track_types_bitfield());
    }
    // optional int64 time_since_last_action_ms = 39;
    if (CheckHasBit(cached_has_bits, 0x04000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_time_since_last_action_ms());
    }
    // optional int64 player_state = 44;
    if (CheckHasBit(cached_has_bits, 0x08000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_player_state());
    }
    // optional int32 max_pacing_rate = 43;
    if (CheckHasBit(cached_has_bits, 0x10000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_max_pacing_rate());
    }
    // optional int32 field48 = 48;
    if (CheckHasBit(cached_has_bits, 0x20000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_field48());
    }
    // optional int32 field50 = 50;
    if (CheckHasBit(cached_has_bits, 0x40000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_field50());
    }
    // optional int32 field51 = 51;
    if (CheckHasBit(cached_has_bits, 0x80000000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_field51());
    }
  }
  cached_has_bits = this_._impl_._has_bits_[1];
  total_size += ::absl::popcount(0x0000301eU & cached_has_bits) * 3;
  if (BatchCheckHasBit(cached_has_bits, 0x000000e1U)) {
    // optional int32 sabr_report_request_cancellation_info = 54;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_sabr_report_request_cancellation_info());
    }
    // optional int64 field57 = 57;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_field57());
    }
    // optional int32 av1_quality_threshold = 59;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_av1_quality_threshold());
    }
    // optional int32 field60 = 60;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_field60());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000f00U)) {
    // optional int32 allow_proxima_live_latency = 64;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_allow_proxima_live_latency());
    }
    // optional int32 sabr_force_proxima = 66;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_sabr_force_proxima());
    }
    // optional int64 sabr_force_max_network_interruption_duration_ms = 68;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int64Size(
                                      this_._internal_sabr_force_max_network_interruption_duration_ms());
    }
    // optional int32 field67 = 67;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      total_size += 2 + ::_pbi::WireFormatLite::Int32Size(
                                      this_._internal_field67());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ClientAbrState::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ClientAbrState*>(&to_msg);
  auto& from = static_cast<const ClientAbrState&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.ClientAbrState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_sabr_license_constraint(from._internal_sabr_license_constraint());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.time_since_last_manual_format_selection_ms_ = from._impl_.time_since_last_manual_format_selection_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.last_manual_direction_ = from._impl_.last_manual_direction_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.last_manual_selected_resolution_ = from._impl_.last_manual_selected_resolution_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.detailed_network_type_ = from._impl_.detailed_network_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.client_viewport_width_ = from._impl_.client_viewport_width_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.client_bitrate_cap_bytes_per_sec_ = from._impl_.client_bitrate_cap_bytes_per_sec_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.client_viewport_height_ = from._impl_.client_viewport_height_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.sticky_resolution_ = from._impl_.sticky_resolution_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.bandwidth_estimate_ = from._impl_.bandwidth_estimate_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      _this->_impl_.min_audio_quality_ = from._impl_.min_audio_quality_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      _this->_impl_.max_audio_quality_ = from._impl_.max_audio_quality_;
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      _this->_impl_.video_quality_setting_ = from._impl_.video_quality_setting_;
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      _this->_impl_.client_viewport_is_flexible_ = from._impl_.client_viewport_is_flexible_;
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      _this->_impl_.data_saver_mode_ = from._impl_.data_saver_mode_;
    }
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      _this->_impl_.player_time_ms_ = from._impl_.player_time_ms_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00ff0000U)) {
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      _this->_impl_.time_since_last_seek_ = from._impl_.time_since_last_seek_;
    }
    if (CheckHasBit(cached_has_bits, 0x00020000U)) {
      _this->_impl_.audio_route_ = from._impl_.audio_route_;
    }
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      _this->_internal_set_audio_track_id(from._internal_audio_track_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      ABSL_DCHECK(from._impl_.media_capabilities_ != nullptr);
      if (_this->_impl_.media_capabilities_ == nullptr) {
        _this->_impl_.media_capabilities_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.media_capabilities_);
      } else {
        _this->_impl_.media_capabilities_->MergeFrom(*from._impl_.media_capabilities_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00100000U)) {
      ABSL_DCHECK(from._impl_.playback_authorization_ != nullptr);
      if (_this->_impl_.playback_authorization_ == nullptr) {
        _this->_impl_.playback_authorization_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.playback_authorization_);
      } else {
        _this->_impl_.playback_authorization_->MergeFrom(*from._impl_.playback_authorization_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00200000U)) {
      _this->_impl_.network_metered_state_ = from._impl_.network_metered_state_;
    }
    if (CheckHasBit(cached_has_bits, 0x00400000U)) {
      _this->_impl_.visibility_ = from._impl_.visibility_;
    }
    if (CheckHasBit(cached_has_bits, 0x00800000U)) {
      _this->_impl_.elapsed_wall_time_ms_ = from._impl_.elapsed_wall_time_ms_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0xff000000U)) {
    if (CheckHasBit(cached_has_bits, 0x01000000U)) {
      _this->_impl_.playback_rate_ = from._impl_.playback_rate_;
    }
    if (CheckHasBit(cached_has_bits, 0x02000000U)) {
      _this->_impl_.enabled_track_types_bitfield_ = from._impl_.enabled_track_types_bitfield_;
    }
    if (CheckHasBit(cached_has_bits, 0x04000000U)) {
      _this->_impl_.time_since_last_action_ms_ = from._impl_.time_since_last_action_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x08000000U)) {
      _this->_impl_.player_state_ = from._impl_.player_state_;
    }
    if (CheckHasBit(cached_has_bits, 0x10000000U)) {
      _this->_impl_.max_pacing_rate_ = from._impl_.max_pacing_rate_;
    }
    if (CheckHasBit(cached_has_bits, 0x20000000U)) {
      _this->_impl_.field48_ = from._impl_.field48_;
    }
    if (CheckHasBit(cached_has_bits, 0x40000000U)) {
      _this->_impl_.field50_ = from._impl_.field50_;
    }
    if (CheckHasBit(cached_has_bits, 0x80000000U)) {
      _this->_impl_.field51_ = from._impl_.field51_;
    }
  }
  cached_has_bits = from._impl_._has_bits_[1];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.sabr_report_request_cancellation_info_ = from._impl_.sabr_report_request_cancellation_info_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.drc_enabled_ = from._impl_.drc_enabled_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.disable_streaming_xhr_ = from._impl_.disable_streaming_xhr_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.prefer_vp9_ = from._impl_.prefer_vp9_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.is_prefetch_ = from._impl_.is_prefetch_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.field57_ = from._impl_.field57_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.av1_quality_threshold_ = from._impl_.av1_quality_threshold_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.field60_ = from._impl_.field60_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00003f00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.allow_proxima_live_latency_ = from._impl_.allow_proxima_live_latency_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.sabr_force_proxima_ = from._impl_.sabr_force_proxima_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      _this->_impl_.sabr_force_max_network_interruption_duration_ms_ = from._impl_.sabr_force_max_network_interruption_duration_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      _this->_impl_.field67_ = from._impl_.field67_;
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      _this->_impl_.sabr_support_quality_constraints_ = from._impl_.sabr_support_quality_constraints_;
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      _this->_impl_.enable_voice_boost_ = from._impl_.enable_voice_boost_;
    }
  }
  _this->_impl_._has_bits_.Or(from._impl_._has_bits_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ClientAbrState::CopyFrom(const ClientAbrState& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.ClientAbrState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClientAbrState::InternalSwap(ClientAbrState* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_._has_bits_[1], other->_impl_._has_bits_[1]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sabr_license_constraint_, &other->_impl_.sabr_license_constraint_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.audio_route_)
      + sizeof(ClientAbrState::_impl_.audio_route_)
      - PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.time_since_last_manual_format_selection_ms_)>(
          reinterpret_cast<char*>(&_impl_.time_since_last_manual_format_selection_ms_),
          reinterpret_cast<char*>(&other->_impl_.time_since_last_manual_format_selection_ms_));
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.audio_track_id_, &other->_impl_.audio_track_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.enable_voice_boost_)
      + sizeof(ClientAbrState::_impl_.enable_voice_boost_)
      - PROTOBUF_FIELD_OFFSET(ClientAbrState, _impl_.media_capabilities_)>(
          reinterpret_cast<char*>(&_impl_.media_capabilities_),
          reinterpret_cast<char*>(&other->_impl_.media_capabilities_));
}

::google::protobuf::Metadata ClientAbrState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_video_5fstreaming_2fclient_5fabr_5fstate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
