// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/media_header.proto
// Protobuf C++ Version: 6.33.4

#include "video_streaming/media_header.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace video_streaming {

inline constexpr MediaHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        video_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        xtags_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        format_id_{nullptr},
        time_range_{nullptr},
        header_id_{0u},
        itag_{0},
        lmt_{::uint64_t{0u}},
        start_range_{::int64_t{0}},
        compression_algorithm_{static_cast< ::misc::CompressionType >(0)},
        is_init_seg_{false},
        bitrate_bps_{::int64_t{0}},
        start_ms_{::int64_t{0}},
        duration_ms_{::int64_t{0}},
        content_length_{::int64_t{0}},
        sequence_lmt_{::uint64_t{0u}},
        sequence_number_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MediaHeader::MediaHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MediaHeader_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MediaHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MediaHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MediaHeaderDefaultTypeInternal() {}
  union {
    MediaHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MediaHeaderDefaultTypeInternal _MediaHeader_default_instance_;
}  // namespace video_streaming
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_video_5fstreaming_2fmedia_5fheader_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_video_5fstreaming_2fmedia_5fheader_2eproto = nullptr;
const ::uint32_t
    TableStruct_video_5fstreaming_2fmedia_5fheader_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_._has_bits_),
        19, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.header_id_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.video_id_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.itag_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.lmt_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.xtags_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.start_range_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.compression_algorithm_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.is_init_seg_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.sequence_number_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.bitrate_bps_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.start_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.duration_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.format_id_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.content_length_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.time_range_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::MediaHeader, _impl_.sequence_lmt_),
        4,
        0,
        5,
        6,
        1,
        7,
        8,
        9,
        15,
        10,
        11,
        12,
        2,
        13,
        3,
        14,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::video_streaming::MediaHeader)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::video_streaming::_MediaHeader_default_instance_._instance,
};
const char descriptor_table_protodef_video_5fstreaming_2fmedia_5fheader_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\"video_streaming/media_header.proto\022\017vi"
    "deo_streaming\032\021misc/common.proto\032 video_"
    "streaming/time_range.proto\"\222\003\n\013MediaHead"
    "er\022\021\n\theader_id\030\001 \001(\r\022\020\n\010video_id\030\002 \001(\t\022"
    "\014\n\004itag\030\003 \001(\005\022\013\n\003lmt\030\004 \001(\004\022\r\n\005xtags\030\005 \001("
    "\t\022\023\n\013start_range\030\006 \001(\003\0224\n\025compression_al"
    "gorithm\030\007 \001(\0162\025.misc.CompressionType\022\023\n\013"
    "is_init_seg\030\010 \001(\010\022\027\n\017sequence_number\030\t \001"
    "(\005\022\023\n\013bitrate_bps\030\n \001(\003\022\020\n\010start_ms\030\013 \001("
    "\003\022\023\n\013duration_ms\030\014 \001(\003\022!\n\tformat_id\030\r \001("
    "\0132\016.misc.FormatId\022\026\n\016content_length\030\016 \001("
    "\003\022.\n\ntime_range\030\017 \001(\0132\032.video_streaming."
    "TimeRange\022\024\n\014sequence_lmt\030\020 \001(\004"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto_deps[2] = {
        &::descriptor_table_misc_2fcommon_2eproto,
        &::descriptor_table_video_5fstreaming_2ftime_5frange_2eproto,
};
static ::absl::once_flag descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto = {
    false,
    false,
    511,
    descriptor_table_protodef_video_5fstreaming_2fmedia_5fheader_2eproto,
    "video_streaming/media_header.proto",
    &descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto_once,
    descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_video_5fstreaming_2fmedia_5fheader_2eproto::offsets,
    file_level_enum_descriptors_video_5fstreaming_2fmedia_5fheader_2eproto,
    file_level_service_descriptors_video_5fstreaming_2fmedia_5fheader_2eproto,
};
namespace video_streaming {
// ===================================================================

class MediaHeader::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MediaHeader>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_._has_bits_);
};

void MediaHeader::clear_format_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.format_id_ != nullptr) _impl_.format_id_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
void MediaHeader::clear_time_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_range_ != nullptr) _impl_.time_range_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
MediaHeader::MediaHeader(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MediaHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.MediaHeader)
}
PROTOBUF_NDEBUG_INLINE MediaHeader::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::MediaHeader& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        video_id_(arena, from.video_id_),
        xtags_(arena, from.xtags_) {}

MediaHeader::MediaHeader(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MediaHeader& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MediaHeader_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MediaHeader* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.format_id_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.format_id_)
                : nullptr;
  _impl_.time_range_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.time_range_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, header_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, header_id_),
           offsetof(Impl_, sequence_number_) -
               offsetof(Impl_, header_id_) +
               sizeof(Impl_::sequence_number_));

  // @@protoc_insertion_point(copy_constructor:video_streaming.MediaHeader)
}
PROTOBUF_NDEBUG_INLINE MediaHeader::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        video_id_(arena),
        xtags_(arena) {}

inline void MediaHeader::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, format_id_),
           0,
           offsetof(Impl_, sequence_number_) -
               offsetof(Impl_, format_id_) +
               sizeof(Impl_::sequence_number_));
}
MediaHeader::~MediaHeader() {
  // @@protoc_insertion_point(destructor:video_streaming.MediaHeader)
  SharedDtor(*this);
}
inline void MediaHeader::SharedDtor(MessageLite& self) {
  MediaHeader& this_ = static_cast<MediaHeader&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.video_id_.Destroy();
  this_._impl_.xtags_.Destroy();
  delete this_._impl_.format_id_;
  delete this_._impl_.time_range_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MediaHeader::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MediaHeader(arena);
}
constexpr auto MediaHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MediaHeader),
                                            alignof(MediaHeader));
}
constexpr auto MediaHeader::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MediaHeader_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MediaHeader::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MediaHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MediaHeader::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MediaHeader>(), &MediaHeader::ByteSizeLong,
              &MediaHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_._cached_size_),
          false,
      },
      &MediaHeader::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MediaHeader_class_data_ =
        MediaHeader::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MediaHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MediaHeader_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MediaHeader_class_data_.tc_table);
  return MediaHeader_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 16, 3, 0, 2>
MediaHeader::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_._has_bits_),
    0, // no _extensions_
    16, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294901760,  // skipmap
    offsetof(decltype(_table_), field_entries),
    16,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    MediaHeader_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::MediaHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint64 sequence_lmt = 16;
    {::_pbi::TcParser::FastV64S2,
     {384, 14, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.sequence_lmt_)}},
    // optional uint32 header_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MediaHeader, _impl_.header_id_), 4>(),
     {8, 4, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.header_id_)}},
    // optional string video_id = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.video_id_)}},
    // optional int32 itag = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MediaHeader, _impl_.itag_), 5>(),
     {24, 5, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.itag_)}},
    // optional uint64 lmt = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MediaHeader, _impl_.lmt_), 6>(),
     {32, 6, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.lmt_)}},
    // optional string xtags = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 1, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.xtags_)}},
    // optional int64 start_range = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MediaHeader, _impl_.start_range_), 7>(),
     {48, 7, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.start_range_)}},
    // optional .misc.CompressionType compression_algorithm = 7;
    {::_pbi::TcParser::FastEr0S1,
     {56, 8, 2,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.compression_algorithm_)}},
    // optional bool is_init_seg = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MediaHeader, _impl_.is_init_seg_), 9>(),
     {64, 9, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.is_init_seg_)}},
    // optional int32 sequence_number = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MediaHeader, _impl_.sequence_number_), 15>(),
     {72, 15, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.sequence_number_)}},
    // optional int64 bitrate_bps = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MediaHeader, _impl_.bitrate_bps_), 10>(),
     {80, 10, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.bitrate_bps_)}},
    // optional int64 start_ms = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MediaHeader, _impl_.start_ms_), 11>(),
     {88, 11, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.start_ms_)}},
    // optional int64 duration_ms = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MediaHeader, _impl_.duration_ms_), 12>(),
     {96, 12, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.duration_ms_)}},
    // optional .misc.FormatId format_id = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 2, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.format_id_)}},
    // optional int64 content_length = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MediaHeader, _impl_.content_length_), 13>(),
     {112, 13, 0,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.content_length_)}},
    // optional .video_streaming.TimeRange time_range = 15;
    {::_pbi::TcParser::FastMtS1,
     {122, 3, 1,
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.time_range_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 header_id = 1;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.header_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional string video_id = 2;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.video_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 itag = 3;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.itag_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint64 lmt = 4;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.lmt_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional string xtags = 5;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.xtags_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int64 start_range = 6;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.start_range_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .misc.CompressionType compression_algorithm = 7;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.compression_algorithm_), _Internal::kHasBitsOffset + 8, 2, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional bool is_init_seg = 8;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.is_init_seg_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional int32 sequence_number = 9;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.sequence_number_), _Internal::kHasBitsOffset + 15, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 bitrate_bps = 10;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.bitrate_bps_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 start_ms = 11;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.start_ms_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 duration_ms = 12;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.duration_ms_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .misc.FormatId format_id = 13;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.format_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int64 content_length = 14;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.content_length_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional .video_streaming.TimeRange time_range = 15;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.time_range_), _Internal::kHasBitsOffset + 3, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional uint64 sequence_lmt = 16;
    {PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.sequence_lmt_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::misc::FormatId>()},
      {::_pbi::TcParser::GetTable<::video_streaming::TimeRange>()},
      {0, 2},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void MediaHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.MediaHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.video_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.xtags_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.format_id_ != nullptr);
      _impl_.format_id_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.time_range_ != nullptr);
      _impl_.time_range_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f0U)) {
    ::memset(&_impl_.header_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.start_range_) -
        reinterpret_cast<char*>(&_impl_.header_id_)) + sizeof(_impl_.start_range_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    ::memset(&_impl_.compression_algorithm_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sequence_number_) -
        reinterpret_cast<char*>(&_impl_.compression_algorithm_)) + sizeof(_impl_.sequence_number_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MediaHeader::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MediaHeader& this_ = static_cast<const MediaHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MediaHeader::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MediaHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.MediaHeader)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 header_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_header_id(), target);
  }

  // optional string video_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_video_id();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional int32 itag = 3;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_itag(), target);
  }

  // optional uint64 lmt = 4;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this_._internal_lmt(), target);
  }

  // optional string xtags = 5;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_xtags();
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional int64 start_range = 6;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
            stream, this_._internal_start_range(), target);
  }

  // optional .misc.CompressionType compression_algorithm = 7;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        7, this_._internal_compression_algorithm(), target);
  }

  // optional bool is_init_seg = 8;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        8, this_._internal_is_init_seg(), target);
  }

  // optional int32 sequence_number = 9;
  if (CheckHasBit(cached_has_bits, 0x00008000U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<9>(
            stream, this_._internal_sequence_number(), target);
  }

  // optional int64 bitrate_bps = 10;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<10>(
            stream, this_._internal_bitrate_bps(), target);
  }

  // optional int64 start_ms = 11;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<11>(
            stream, this_._internal_start_ms(), target);
  }

  // optional int64 duration_ms = 12;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<12>(
            stream, this_._internal_duration_ms(), target);
  }

  // optional .misc.FormatId format_id = 13;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        13, *this_._impl_.format_id_, this_._impl_.format_id_->GetCachedSize(), target,
        stream);
  }

  // optional int64 content_length = 14;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<14>(
            stream, this_._internal_content_length(), target);
  }

  // optional .video_streaming.TimeRange time_range = 15;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        15, *this_._impl_.time_range_, this_._impl_.time_range_->GetCachedSize(), target,
        stream);
  }

  // optional uint64 sequence_lmt = 16;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        16, this_._internal_sequence_lmt(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.MediaHeader)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MediaHeader::ByteSizeLong(const MessageLite& base) {
  const MediaHeader& this_ = static_cast<const MediaHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MediaHeader::ByteSizeLong() const {
  const MediaHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.MediaHeader)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000200U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // optional string video_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_video_id());
    }
    // optional string xtags = 5;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_xtags());
    }
    // optional .misc.FormatId format_id = 13;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.format_id_);
    }
    // optional .video_streaming.TimeRange time_range = 15;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.time_range_);
    }
    // optional uint32 header_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_header_id());
    }
    // optional int32 itag = 3;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_itag());
    }
    // optional uint64 lmt = 4;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_lmt());
    }
    // optional int64 start_range = 6;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_start_range());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000fd00U)) {
    // optional .misc.CompressionType compression_algorithm = 7;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_compression_algorithm());
    }
    // optional int64 bitrate_bps = 10;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_bitrate_bps());
    }
    // optional int64 start_ms = 11;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_start_ms());
    }
    // optional int64 duration_ms = 12;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_duration_ms());
    }
    // optional int64 content_length = 14;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_content_length());
    }
    // optional uint64 sequence_lmt = 16;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      total_size += 2 + ::_pbi::WireFormatLite::UInt64Size(
                                      this_._internal_sequence_lmt());
    }
    // optional int32 sequence_number = 9;
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_sequence_number());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MediaHeader::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MediaHeader*>(&to_msg);
  auto& from = static_cast<const MediaHeader&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.MediaHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_video_id(from._internal_video_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_xtags(from._internal_xtags());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.format_id_ != nullptr);
      if (_this->_impl_.format_id_ == nullptr) {
        _this->_impl_.format_id_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.format_id_);
      } else {
        _this->_impl_.format_id_->MergeFrom(*from._impl_.format_id_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.time_range_ != nullptr);
      if (_this->_impl_.time_range_ == nullptr) {
        _this->_impl_.time_range_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.time_range_);
      } else {
        _this->_impl_.time_range_->MergeFrom(*from._impl_.time_range_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.header_id_ = from._impl_.header_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.itag_ = from._impl_.itag_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.lmt_ = from._impl_.lmt_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.start_range_ = from._impl_.start_range_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.compression_algorithm_ = from._impl_.compression_algorithm_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.is_init_seg_ = from._impl_.is_init_seg_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      _this->_impl_.bitrate_bps_ = from._impl_.bitrate_bps_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      _this->_impl_.start_ms_ = from._impl_.start_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      _this->_impl_.duration_ms_ = from._impl_.duration_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      _this->_impl_.content_length_ = from._impl_.content_length_;
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      _this->_impl_.sequence_lmt_ = from._impl_.sequence_lmt_;
    }
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      _this->_impl_.sequence_number_ = from._impl_.sequence_number_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MediaHeader::CopyFrom(const MediaHeader& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.MediaHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MediaHeader::InternalSwap(MediaHeader* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.video_id_, &other->_impl_.video_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.xtags_, &other->_impl_.xtags_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.sequence_number_)
      + sizeof(MediaHeader::_impl_.sequence_number_)
      - PROTOBUF_FIELD_OFFSET(MediaHeader, _impl_.format_id_)>(
          reinterpret_cast<char*>(&_impl_.format_id_),
          reinterpret_cast<char*>(&other->_impl_.format_id_));
}

::google::protobuf::Metadata MediaHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_video_5fstreaming_2fmedia_5fheader_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
