// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/onesie_header_type.proto
// Protobuf C++ Version: 6.33.4

#ifndef video_5fstreaming_2fonesie_5fheader_5ftype_2eproto_2epb_2eh
#define video_5fstreaming_2fonesie_5fheader_5ftype_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_video_5fstreaming_2fonesie_5fheader_5ftype_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fstreaming_2fonesie_5fheader_5ftype_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_video_5fstreaming_2fonesie_5fheader_5ftype_2eproto;
}  // extern "C"
namespace video_streaming {
enum OnesieHeaderType : int;
extern const uint32_t OnesieHeaderType_internal_data_[];
}  // namespace video_streaming
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::video_streaming::OnesieHeaderType_internal_data_>
    internal::EnumTraitsImpl::value<::video_streaming::OnesieHeaderType>;
}  // namespace protobuf
}  // namespace google

namespace video_streaming {
enum OnesieHeaderType : int {
  ONESIE_PLAYER_RESPONSE = 0,
  MEDIA = 1,
  MEDIA_DECRYPTION_KEY = 2,
  CLEAR_MEDIA = 3,
  CLEAR_INIT_SEGMENT = 4,
  ACK = 5,
  MEDIA_STREAMER_HOSTNAME = 6,
  MEDIA_SIZE_HINT = 7,
  PLAYER_SERVICE_RESPONSE_PUSH_URL = 8,
  LAST_HIGH_PRIORITY_HINT = 9,
  STREAM_METADATA = 16,
  ENCRYPTED_INNERTUBE_RESPONSE_PART = 25,
};

extern const uint32_t OnesieHeaderType_internal_data_[];
inline constexpr OnesieHeaderType OnesieHeaderType_MIN =
    static_cast<OnesieHeaderType>(0);
inline constexpr OnesieHeaderType OnesieHeaderType_MAX =
    static_cast<OnesieHeaderType>(25);
inline bool OnesieHeaderType_IsValid(int value) {
  return 0 <= value && value <= 25 && ((33620991u >> value) & 1) != 0;
}
inline constexpr int OnesieHeaderType_ARRAYSIZE = 25 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL OnesieHeaderType_descriptor();
template <typename T>
const ::std::string& OnesieHeaderType_Name(T value) {
  static_assert(::std::is_same<T, OnesieHeaderType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to OnesieHeaderType_Name().");
  return ::google::protobuf::internal::NameOfEnum(OnesieHeaderType_descriptor(), value);
}
inline bool OnesieHeaderType_Parse(
    ::absl::string_view name, OnesieHeaderType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<OnesieHeaderType>(OnesieHeaderType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::video_streaming::OnesieHeaderType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::video_streaming::OnesieHeaderType>() {
  return ::video_streaming::OnesieHeaderType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // video_5fstreaming_2fonesie_5fheader_5ftype_2eproto_2epb_2eh
