// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: video_streaming/onesie_header_type.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum VideoStreaming_OnesieHeaderType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case onesiePlayerResponse = 0
  case media = 1
  case mediaDecryptionKey = 2
  case clearMedia = 3
  case clearInitSegment = 4
  case ack = 5
  case mediaStreamerHostname = 6
  case mediaSizeHint = 7
  case playerServiceResponsePushURL = 8
  case lastHighPriorityHint = 9
  case streamMetadata = 16
  case encryptedInnertubeResponsePart = 25

  init() {
    self = .onesiePlayerResponse
  }

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension VideoStreaming_OnesieHeaderType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ONESIE_PLAYER_RESPONSE\0\u{1}MEDIA\0\u{1}MEDIA_DECRYPTION_KEY\0\u{1}CLEAR_MEDIA\0\u{1}CLEAR_INIT_SEGMENT\0\u{1}ACK\0\u{1}MEDIA_STREAMER_HOSTNAME\0\u{1}MEDIA_SIZE_HINT\0\u{1}PLAYER_SERVICE_RESPONSE_PUSH_URL\0\u{1}LAST_HIGH_PRIORITY_HINT\0\u{2}\u{7}STREAM_METADATA\0\u{2}\u{9}ENCRYPTED_INNERTUBE_RESPONSE_PART\0")
}
