// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/buffered_range.proto
// Protobuf C++ Version: 6.33.4

#ifndef video_5fstreaming_2fbuffered_5frange_2eproto_2epb_2eh
#define video_5fstreaming_2fbuffered_5frange_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "misc/common.pb.h"
#include "video_streaming/time_range.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_video_5fstreaming_2fbuffered_5frange_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fstreaming_2fbuffered_5frange_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_video_5fstreaming_2fbuffered_5frange_2eproto;
}  // extern "C"
namespace video_streaming {
class BufferedRange;
struct BufferedRangeDefaultTypeInternal;
extern BufferedRangeDefaultTypeInternal _BufferedRange_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BufferedRange_class_data_;
class BufferedRange_UnknownMessage1;
struct BufferedRange_UnknownMessage1DefaultTypeInternal;
extern BufferedRange_UnknownMessage1DefaultTypeInternal _BufferedRange_UnknownMessage1_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BufferedRange_UnknownMessage1_class_data_;
class BufferedRange_UnknownMessage1_UnknownInnerMessage;
struct BufferedRange_UnknownMessage1_UnknownInnerMessageDefaultTypeInternal;
extern BufferedRange_UnknownMessage1_UnknownInnerMessageDefaultTypeInternal _BufferedRange_UnknownMessage1_UnknownInnerMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BufferedRange_UnknownMessage1_UnknownInnerMessage_class_data_;
class BufferedRange_UnknownMessage2;
struct BufferedRange_UnknownMessage2DefaultTypeInternal;
extern BufferedRange_UnknownMessage2DefaultTypeInternal _BufferedRange_UnknownMessage2_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BufferedRange_UnknownMessage2_class_data_;
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace video_streaming {

// ===================================================================


// -------------------------------------------------------------------

class BufferedRange_UnknownMessage2 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.BufferedRange.UnknownMessage2) */ {
 public:
  inline BufferedRange_UnknownMessage2() : BufferedRange_UnknownMessage2(nullptr) {}
  ~BufferedRange_UnknownMessage2() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BufferedRange_UnknownMessage2* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BufferedRange_UnknownMessage2));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BufferedRange_UnknownMessage2(::google::protobuf::internal::ConstantInitialized);

  inline BufferedRange_UnknownMessage2(const BufferedRange_UnknownMessage2& from) : BufferedRange_UnknownMessage2(nullptr, from) {}
  inline BufferedRange_UnknownMessage2(BufferedRange_UnknownMessage2&& from) noexcept
      : BufferedRange_UnknownMessage2(nullptr, ::std::move(from)) {}
  inline BufferedRange_UnknownMessage2& operator=(const BufferedRange_UnknownMessage2& from) {
    CopyFrom(from);
    return *this;
  }
  inline BufferedRange_UnknownMessage2& operator=(BufferedRange_UnknownMessage2&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BufferedRange_UnknownMessage2& default_instance() {
    return *reinterpret_cast<const BufferedRange_UnknownMessage2*>(
        &_BufferedRange_UnknownMessage2_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(BufferedRange_UnknownMessage2& a, BufferedRange_UnknownMessage2& b) { a.Swap(&b); }
  inline void Swap(BufferedRange_UnknownMessage2* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BufferedRange_UnknownMessage2* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BufferedRange_UnknownMessage2* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BufferedRange_UnknownMessage2>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BufferedRange_UnknownMessage2& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BufferedRange_UnknownMessage2& from) { BufferedRange_UnknownMessage2::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BufferedRange_UnknownMessage2* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.BufferedRange.UnknownMessage2"; }

  explicit BufferedRange_UnknownMessage2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BufferedRange_UnknownMessage2(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BufferedRange_UnknownMessage2& from);
  BufferedRange_UnknownMessage2(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BufferedRange_UnknownMessage2&& from) noexcept
      : BufferedRange_UnknownMessage2(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kField1FieldNumber = 1,
    kField2FieldNumber = 2,
    kField3FieldNumber = 3,
  };
  // optional int32 field1 = 1;
  bool has_field1() const;
  void clear_field1() ;
  ::int32_t field1() const;
  void set_field1(::int32_t value);

  private:
  ::int32_t _internal_field1() const;
  void _internal_set_field1(::int32_t value);

  public:
  // optional int32 field2 = 2;
  bool has_field2() const;
  void clear_field2() ;
  ::int32_t field2() const;
  void set_field2(::int32_t value);

  private:
  ::int32_t _internal_field2() const;
  void _internal_set_field2(::int32_t value);

  public:
  // optional int32 field3 = 3;
  bool has_field3() const;
  void clear_field3() ;
  ::int32_t field3() const;
  void set_field3(::int32_t value);

  private:
  ::int32_t _internal_field3() const;
  void _internal_set_field3(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.BufferedRange.UnknownMessage2)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BufferedRange_UnknownMessage2& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t field1_;
    ::int32_t field2_;
    ::int32_t field3_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fbuffered_5frange_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BufferedRange_UnknownMessage2_class_data_;
// -------------------------------------------------------------------

class BufferedRange_UnknownMessage1_UnknownInnerMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage) */ {
 public:
  inline BufferedRange_UnknownMessage1_UnknownInnerMessage() : BufferedRange_UnknownMessage1_UnknownInnerMessage(nullptr) {}
  ~BufferedRange_UnknownMessage1_UnknownInnerMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BufferedRange_UnknownMessage1_UnknownInnerMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BufferedRange_UnknownMessage1_UnknownInnerMessage(::google::protobuf::internal::ConstantInitialized);

  inline BufferedRange_UnknownMessage1_UnknownInnerMessage(const BufferedRange_UnknownMessage1_UnknownInnerMessage& from) : BufferedRange_UnknownMessage1_UnknownInnerMessage(nullptr, from) {}
  inline BufferedRange_UnknownMessage1_UnknownInnerMessage(BufferedRange_UnknownMessage1_UnknownInnerMessage&& from) noexcept
      : BufferedRange_UnknownMessage1_UnknownInnerMessage(nullptr, ::std::move(from)) {}
  inline BufferedRange_UnknownMessage1_UnknownInnerMessage& operator=(const BufferedRange_UnknownMessage1_UnknownInnerMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline BufferedRange_UnknownMessage1_UnknownInnerMessage& operator=(BufferedRange_UnknownMessage1_UnknownInnerMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BufferedRange_UnknownMessage1_UnknownInnerMessage& default_instance() {
    return *reinterpret_cast<const BufferedRange_UnknownMessage1_UnknownInnerMessage*>(
        &_BufferedRange_UnknownMessage1_UnknownInnerMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BufferedRange_UnknownMessage1_UnknownInnerMessage& a, BufferedRange_UnknownMessage1_UnknownInnerMessage& b) { a.Swap(&b); }
  inline void Swap(BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BufferedRange_UnknownMessage1_UnknownInnerMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BufferedRange_UnknownMessage1_UnknownInnerMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BufferedRange_UnknownMessage1_UnknownInnerMessage& from) { BufferedRange_UnknownMessage1_UnknownInnerMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage"; }

  explicit BufferedRange_UnknownMessage1_UnknownInnerMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BufferedRange_UnknownMessage1_UnknownInnerMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BufferedRange_UnknownMessage1_UnknownInnerMessage& from);
  BufferedRange_UnknownMessage1_UnknownInnerMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BufferedRange_UnknownMessage1_UnknownInnerMessage&& from) noexcept
      : BufferedRange_UnknownMessage1_UnknownInnerMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVideoIdFieldNumber = 1,
    kLmtFieldNumber = 2,
  };
  // optional string video_id = 1;
  bool has_video_id() const;
  void clear_video_id() ;
  const ::std::string& video_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_video_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_video_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_video_id();
  void set_allocated_video_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_video_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_video_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_video_id();

  public:
  // optional uint64 lmt = 2;
  bool has_lmt() const;
  void clear_lmt() ;
  ::uint64_t lmt() const;
  void set_lmt(::uint64_t value);

  private:
  ::uint64_t _internal_lmt() const;
  void _internal_set_lmt(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BufferedRange_UnknownMessage1_UnknownInnerMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr video_id_;
    ::uint64_t lmt_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fbuffered_5frange_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BufferedRange_UnknownMessage1_UnknownInnerMessage_class_data_;
// -------------------------------------------------------------------

class BufferedRange_UnknownMessage1 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.BufferedRange.UnknownMessage1) */ {
 public:
  inline BufferedRange_UnknownMessage1() : BufferedRange_UnknownMessage1(nullptr) {}
  ~BufferedRange_UnknownMessage1() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BufferedRange_UnknownMessage1* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BufferedRange_UnknownMessage1));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BufferedRange_UnknownMessage1(::google::protobuf::internal::ConstantInitialized);

  inline BufferedRange_UnknownMessage1(const BufferedRange_UnknownMessage1& from) : BufferedRange_UnknownMessage1(nullptr, from) {}
  inline BufferedRange_UnknownMessage1(BufferedRange_UnknownMessage1&& from) noexcept
      : BufferedRange_UnknownMessage1(nullptr, ::std::move(from)) {}
  inline BufferedRange_UnknownMessage1& operator=(const BufferedRange_UnknownMessage1& from) {
    CopyFrom(from);
    return *this;
  }
  inline BufferedRange_UnknownMessage1& operator=(BufferedRange_UnknownMessage1&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BufferedRange_UnknownMessage1& default_instance() {
    return *reinterpret_cast<const BufferedRange_UnknownMessage1*>(
        &_BufferedRange_UnknownMessage1_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BufferedRange_UnknownMessage1& a, BufferedRange_UnknownMessage1& b) { a.Swap(&b); }
  inline void Swap(BufferedRange_UnknownMessage1* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BufferedRange_UnknownMessage1* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BufferedRange_UnknownMessage1* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BufferedRange_UnknownMessage1>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BufferedRange_UnknownMessage1& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BufferedRange_UnknownMessage1& from) { BufferedRange_UnknownMessage1::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BufferedRange_UnknownMessage1* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.BufferedRange.UnknownMessage1"; }

  explicit BufferedRange_UnknownMessage1(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BufferedRange_UnknownMessage1(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BufferedRange_UnknownMessage1& from);
  BufferedRange_UnknownMessage1(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BufferedRange_UnknownMessage1&& from) noexcept
      : BufferedRange_UnknownMessage1(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using UnknownInnerMessage = BufferedRange_UnknownMessage1_UnknownInnerMessage;

  // accessors -------------------------------------------------------
  enum : int {
    kField1FieldNumber = 1,
  };
  // repeated .video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage field1 = 1;
  int field1_size() const;
  private:
  int _internal_field1_size() const;

  public:
  void clear_field1() ;
  ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL mutable_field1(int index);
  ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>* PROTOBUF_NONNULL mutable_field1();

  private:
  const ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>& _internal_field1() const;
  ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>* PROTOBUF_NONNULL _internal_mutable_field1();
  public:
  const ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage& field1(int index) const;
  ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL add_field1();
  const ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>& field1() const;
  // @@protoc_insertion_point(class_scope:video_streaming.BufferedRange.UnknownMessage1)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BufferedRange_UnknownMessage1& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage > field1_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fbuffered_5frange_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BufferedRange_UnknownMessage1_class_data_;
// -------------------------------------------------------------------

class BufferedRange final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.BufferedRange) */ {
 public:
  inline BufferedRange() : BufferedRange(nullptr) {}
  ~BufferedRange() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BufferedRange* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BufferedRange));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BufferedRange(::google::protobuf::internal::ConstantInitialized);

  inline BufferedRange(const BufferedRange& from) : BufferedRange(nullptr, from) {}
  inline BufferedRange(BufferedRange&& from) noexcept
      : BufferedRange(nullptr, ::std::move(from)) {}
  inline BufferedRange& operator=(const BufferedRange& from) {
    CopyFrom(from);
    return *this;
  }
  inline BufferedRange& operator=(BufferedRange&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BufferedRange& default_instance() {
    return *reinterpret_cast<const BufferedRange*>(
        &_BufferedRange_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BufferedRange& a, BufferedRange& b) { a.Swap(&b); }
  inline void Swap(BufferedRange* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BufferedRange* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BufferedRange* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BufferedRange>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BufferedRange& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BufferedRange& from) { BufferedRange::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BufferedRange* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.BufferedRange"; }

  explicit BufferedRange(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BufferedRange(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BufferedRange& from);
  BufferedRange(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BufferedRange&& from) noexcept
      : BufferedRange(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using UnknownMessage1 = BufferedRange_UnknownMessage1;
  using UnknownMessage2 = BufferedRange_UnknownMessage2;

  // accessors -------------------------------------------------------
  enum : int {
    kFormatIdFieldNumber = 1,
    kTimeRangeFieldNumber = 6,
    kField9FieldNumber = 9,
    kField11FieldNumber = 11,
    kField12FieldNumber = 12,
    kStartTimeMsFieldNumber = 2,
    kDurationMsFieldNumber = 3,
    kStartSegmentIndexFieldNumber = 4,
    kEndSegmentIndexFieldNumber = 5,
  };
  // required .misc.FormatId format_id = 1;
  bool has_format_id() const;
  void clear_format_id() ;
  const ::misc::FormatId& format_id() const;
  [[nodiscard]] ::misc::FormatId* PROTOBUF_NULLABLE release_format_id();
  ::misc::FormatId* PROTOBUF_NONNULL mutable_format_id();
  void set_allocated_format_id(::misc::FormatId* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_format_id(::misc::FormatId* PROTOBUF_NULLABLE value);
  ::misc::FormatId* PROTOBUF_NULLABLE unsafe_arena_release_format_id();

  private:
  const ::misc::FormatId& _internal_format_id() const;
  ::misc::FormatId* PROTOBUF_NONNULL _internal_mutable_format_id();

  public:
  // optional .video_streaming.TimeRange time_range = 6;
  bool has_time_range() const;
  void clear_time_range() ;
  const ::video_streaming::TimeRange& time_range() const;
  [[nodiscard]] ::video_streaming::TimeRange* PROTOBUF_NULLABLE release_time_range();
  ::video_streaming::TimeRange* PROTOBUF_NONNULL mutable_time_range();
  void set_allocated_time_range(::video_streaming::TimeRange* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_time_range(::video_streaming::TimeRange* PROTOBUF_NULLABLE value);
  ::video_streaming::TimeRange* PROTOBUF_NULLABLE unsafe_arena_release_time_range();

  private:
  const ::video_streaming::TimeRange& _internal_time_range() const;
  ::video_streaming::TimeRange* PROTOBUF_NONNULL _internal_mutable_time_range();

  public:
  // optional .video_streaming.BufferedRange.UnknownMessage1 field9 = 9;
  bool has_field9() const;
  void clear_field9() ;
  const ::video_streaming::BufferedRange_UnknownMessage1& field9() const;
  [[nodiscard]] ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE release_field9();
  ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NONNULL mutable_field9();
  void set_allocated_field9(::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_field9(::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE value);
  ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE unsafe_arena_release_field9();

  private:
  const ::video_streaming::BufferedRange_UnknownMessage1& _internal_field9() const;
  ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NONNULL _internal_mutable_field9();

  public:
  // optional .video_streaming.BufferedRange.UnknownMessage2 field11 = 11;
  bool has_field11() const;
  void clear_field11() ;
  const ::video_streaming::BufferedRange_UnknownMessage2& field11() const;
  [[nodiscard]] ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE release_field11();
  ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL mutable_field11();
  void set_allocated_field11(::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_field11(::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value);
  ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE unsafe_arena_release_field11();

  private:
  const ::video_streaming::BufferedRange_UnknownMessage2& _internal_field11() const;
  ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL _internal_mutable_field11();

  public:
  // optional .video_streaming.BufferedRange.UnknownMessage2 field12 = 12;
  bool has_field12() const;
  void clear_field12() ;
  const ::video_streaming::BufferedRange_UnknownMessage2& field12() const;
  [[nodiscard]] ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE release_field12();
  ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL mutable_field12();
  void set_allocated_field12(::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_field12(::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value);
  ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE unsafe_arena_release_field12();

  private:
  const ::video_streaming::BufferedRange_UnknownMessage2& _internal_field12() const;
  ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL _internal_mutable_field12();

  public:
  // required int64 start_time_ms = 2;
  bool has_start_time_ms() const;
  void clear_start_time_ms() ;
  ::int64_t start_time_ms() const;
  void set_start_time_ms(::int64_t value);

  private:
  ::int64_t _internal_start_time_ms() const;
  void _internal_set_start_time_ms(::int64_t value);

  public:
  // required int64 duration_ms = 3;
  bool has_duration_ms() const;
  void clear_duration_ms() ;
  ::int64_t duration_ms() const;
  void set_duration_ms(::int64_t value);

  private:
  ::int64_t _internal_duration_ms() const;
  void _internal_set_duration_ms(::int64_t value);

  public:
  // required int32 start_segment_index = 4;
  bool has_start_segment_index() const;
  void clear_start_segment_index() ;
  ::int32_t start_segment_index() const;
  void set_start_segment_index(::int32_t value);

  private:
  ::int32_t _internal_start_segment_index() const;
  void _internal_set_start_segment_index(::int32_t value);

  public:
  // required int32 end_segment_index = 5;
  bool has_end_segment_index() const;
  void clear_end_segment_index() ;
  ::int32_t end_segment_index() const;
  void set_end_segment_index(::int32_t value);

  private:
  ::int32_t _internal_end_segment_index() const;
  void _internal_set_end_segment_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.BufferedRange)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   5, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BufferedRange& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::misc::FormatId* PROTOBUF_NULLABLE format_id_;
    ::video_streaming::TimeRange* PROTOBUF_NULLABLE time_range_;
    ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE field9_;
    ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE field11_;
    ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE field12_;
    ::int64_t start_time_ms_;
    ::int64_t duration_ms_;
    ::int32_t start_segment_index_;
    ::int32_t end_segment_index_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fbuffered_5frange_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BufferedRange_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BufferedRange_UnknownMessage1_UnknownInnerMessage

// optional string video_id = 1;
inline bool BufferedRange_UnknownMessage1_UnknownInnerMessage::has_video_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BufferedRange_UnknownMessage1_UnknownInnerMessage::clear_video_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.video_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BufferedRange_UnknownMessage1_UnknownInnerMessage::video_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.video_id)
  return _internal_video_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BufferedRange_UnknownMessage1_UnknownInnerMessage::set_video_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.video_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.video_id)
}
inline ::std::string* PROTOBUF_NONNULL BufferedRange_UnknownMessage1_UnknownInnerMessage::mutable_video_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_video_id();
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.video_id)
  return _s;
}
inline const ::std::string& BufferedRange_UnknownMessage1_UnknownInnerMessage::_internal_video_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.video_id_.Get();
}
inline void BufferedRange_UnknownMessage1_UnknownInnerMessage::_internal_set_video_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.video_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BufferedRange_UnknownMessage1_UnknownInnerMessage::_internal_mutable_video_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.video_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BufferedRange_UnknownMessage1_UnknownInnerMessage::release_video_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.video_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.video_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.video_id_.Set("", GetArena());
  }
  return released;
}
inline void BufferedRange_UnknownMessage1_UnknownInnerMessage::set_allocated_video_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.video_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.video_id_.IsDefault()) {
    _impl_.video_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.video_id)
}

// optional uint64 lmt = 2;
inline bool BufferedRange_UnknownMessage1_UnknownInnerMessage::has_lmt() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void BufferedRange_UnknownMessage1_UnknownInnerMessage::clear_lmt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lmt_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t BufferedRange_UnknownMessage1_UnknownInnerMessage::lmt() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.lmt)
  return _internal_lmt();
}
inline void BufferedRange_UnknownMessage1_UnknownInnerMessage::set_lmt(::uint64_t value) {
  _internal_set_lmt(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage.lmt)
}
inline ::uint64_t BufferedRange_UnknownMessage1_UnknownInnerMessage::_internal_lmt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lmt_;
}
inline void BufferedRange_UnknownMessage1_UnknownInnerMessage::_internal_set_lmt(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lmt_ = value;
}

// -------------------------------------------------------------------

// BufferedRange_UnknownMessage1

// repeated .video_streaming.BufferedRange.UnknownMessage1.UnknownInnerMessage field1 = 1;
inline int BufferedRange_UnknownMessage1::_internal_field1_size() const {
  return _internal_field1().size();
}
inline int BufferedRange_UnknownMessage1::field1_size() const {
  return _internal_field1_size();
}
inline void BufferedRange_UnknownMessage1::clear_field1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field1_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL BufferedRange_UnknownMessage1::mutable_field1(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.UnknownMessage1.field1)
  return _internal_mutable_field1()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>* PROTOBUF_NONNULL BufferedRange_UnknownMessage1::mutable_field1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:video_streaming.BufferedRange.UnknownMessage1.field1)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_field1();
}
inline const ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage& BufferedRange_UnknownMessage1::field1(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.UnknownMessage1.field1)
  return _internal_field1().Get(index);
}
inline ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage* PROTOBUF_NONNULL BufferedRange_UnknownMessage1::add_field1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage* _add =
      _internal_mutable_field1()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:video_streaming.BufferedRange.UnknownMessage1.field1)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>& BufferedRange_UnknownMessage1::field1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:video_streaming.BufferedRange.UnknownMessage1.field1)
  return _internal_field1();
}
inline const ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>&
BufferedRange_UnknownMessage1::_internal_field1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field1_;
}
inline ::google::protobuf::RepeatedPtrField<::video_streaming::BufferedRange_UnknownMessage1_UnknownInnerMessage>* PROTOBUF_NONNULL
BufferedRange_UnknownMessage1::_internal_mutable_field1() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.field1_;
}

// -------------------------------------------------------------------

// BufferedRange_UnknownMessage2

// optional int32 field1 = 1;
inline bool BufferedRange_UnknownMessage2::has_field1() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BufferedRange_UnknownMessage2::clear_field1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field1_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t BufferedRange_UnknownMessage2::field1() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.UnknownMessage2.field1)
  return _internal_field1();
}
inline void BufferedRange_UnknownMessage2::set_field1(::int32_t value) {
  _internal_set_field1(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.UnknownMessage2.field1)
}
inline ::int32_t BufferedRange_UnknownMessage2::_internal_field1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field1_;
}
inline void BufferedRange_UnknownMessage2::_internal_set_field1(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field1_ = value;
}

// optional int32 field2 = 2;
inline bool BufferedRange_UnknownMessage2::has_field2() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void BufferedRange_UnknownMessage2::clear_field2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field2_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t BufferedRange_UnknownMessage2::field2() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.UnknownMessage2.field2)
  return _internal_field2();
}
inline void BufferedRange_UnknownMessage2::set_field2(::int32_t value) {
  _internal_set_field2(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.UnknownMessage2.field2)
}
inline ::int32_t BufferedRange_UnknownMessage2::_internal_field2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field2_;
}
inline void BufferedRange_UnknownMessage2::_internal_set_field2(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field2_ = value;
}

// optional int32 field3 = 3;
inline bool BufferedRange_UnknownMessage2::has_field3() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void BufferedRange_UnknownMessage2::clear_field3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field3_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t BufferedRange_UnknownMessage2::field3() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.UnknownMessage2.field3)
  return _internal_field3();
}
inline void BufferedRange_UnknownMessage2::set_field3(::int32_t value) {
  _internal_set_field3(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.UnknownMessage2.field3)
}
inline ::int32_t BufferedRange_UnknownMessage2::_internal_field3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field3_;
}
inline void BufferedRange_UnknownMessage2::_internal_set_field3(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field3_ = value;
}

// -------------------------------------------------------------------

// BufferedRange

// required .misc.FormatId format_id = 1;
inline bool BufferedRange::has_format_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.format_id_ != nullptr);
  return value;
}
inline const ::misc::FormatId& BufferedRange::_internal_format_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::misc::FormatId* p = _impl_.format_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::misc::FormatId&>(::misc::_FormatId_default_instance_);
}
inline const ::misc::FormatId& BufferedRange::format_id() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.format_id)
  return _internal_format_id();
}
inline void BufferedRange::unsafe_arena_set_allocated_format_id(
    ::misc::FormatId* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.format_id_);
  }
  _impl_.format_id_ = reinterpret_cast<::misc::FormatId*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.BufferedRange.format_id)
}
inline ::misc::FormatId* PROTOBUF_NULLABLE BufferedRange::release_format_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::misc::FormatId* released = _impl_.format_id_;
  _impl_.format_id_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::misc::FormatId* PROTOBUF_NULLABLE BufferedRange::unsafe_arena_release_format_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.BufferedRange.format_id)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::misc::FormatId* temp = _impl_.format_id_;
  _impl_.format_id_ = nullptr;
  return temp;
}
inline ::misc::FormatId* PROTOBUF_NONNULL BufferedRange::_internal_mutable_format_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.format_id_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::misc::FormatId>(GetArena());
    _impl_.format_id_ = reinterpret_cast<::misc::FormatId*>(p);
  }
  return _impl_.format_id_;
}
inline ::misc::FormatId* PROTOBUF_NONNULL BufferedRange::mutable_format_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::misc::FormatId* _msg = _internal_mutable_format_id();
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.format_id)
  return _msg;
}
inline void BufferedRange::set_allocated_format_id(::misc::FormatId* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.format_id_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.format_id_ = reinterpret_cast<::misc::FormatId*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.BufferedRange.format_id)
}

// required int64 start_time_ms = 2;
inline bool BufferedRange::has_start_time_ms() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void BufferedRange::clear_start_time_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_time_ms_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int64_t BufferedRange::start_time_ms() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.start_time_ms)
  return _internal_start_time_ms();
}
inline void BufferedRange::set_start_time_ms(::int64_t value) {
  _internal_set_start_time_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.start_time_ms)
}
inline ::int64_t BufferedRange::_internal_start_time_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_time_ms_;
}
inline void BufferedRange::_internal_set_start_time_ms(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_time_ms_ = value;
}

// required int64 duration_ms = 3;
inline bool BufferedRange::has_duration_ms() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void BufferedRange::clear_duration_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_ms_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int64_t BufferedRange::duration_ms() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.duration_ms)
  return _internal_duration_ms();
}
inline void BufferedRange::set_duration_ms(::int64_t value) {
  _internal_set_duration_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.duration_ms)
}
inline ::int64_t BufferedRange::_internal_duration_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.duration_ms_;
}
inline void BufferedRange::_internal_set_duration_ms(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_ms_ = value;
}

// required int32 start_segment_index = 4;
inline bool BufferedRange::has_start_segment_index() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void BufferedRange::clear_start_segment_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_segment_index_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t BufferedRange::start_segment_index() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.start_segment_index)
  return _internal_start_segment_index();
}
inline void BufferedRange::set_start_segment_index(::int32_t value) {
  _internal_set_start_segment_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.start_segment_index)
}
inline ::int32_t BufferedRange::_internal_start_segment_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_segment_index_;
}
inline void BufferedRange::_internal_set_start_segment_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_segment_index_ = value;
}

// required int32 end_segment_index = 5;
inline bool BufferedRange::has_end_segment_index() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void BufferedRange::clear_end_segment_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_segment_index_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int32_t BufferedRange::end_segment_index() const {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.end_segment_index)
  return _internal_end_segment_index();
}
inline void BufferedRange::set_end_segment_index(::int32_t value) {
  _internal_set_end_segment_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:video_streaming.BufferedRange.end_segment_index)
}
inline ::int32_t BufferedRange::_internal_end_segment_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_segment_index_;
}
inline void BufferedRange::_internal_set_end_segment_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_segment_index_ = value;
}

// optional .video_streaming.TimeRange time_range = 6;
inline bool BufferedRange::has_time_range() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.time_range_ != nullptr);
  return value;
}
inline const ::video_streaming::TimeRange& BufferedRange::_internal_time_range() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::TimeRange* p = _impl_.time_range_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::TimeRange&>(::video_streaming::_TimeRange_default_instance_);
}
inline const ::video_streaming::TimeRange& BufferedRange::time_range() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.time_range)
  return _internal_time_range();
}
inline void BufferedRange::unsafe_arena_set_allocated_time_range(
    ::video_streaming::TimeRange* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.time_range_);
  }
  _impl_.time_range_ = reinterpret_cast<::video_streaming::TimeRange*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.BufferedRange.time_range)
}
inline ::video_streaming::TimeRange* PROTOBUF_NULLABLE BufferedRange::release_time_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::video_streaming::TimeRange* released = _impl_.time_range_;
  _impl_.time_range_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::TimeRange* PROTOBUF_NULLABLE BufferedRange::unsafe_arena_release_time_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.BufferedRange.time_range)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::video_streaming::TimeRange* temp = _impl_.time_range_;
  _impl_.time_range_ = nullptr;
  return temp;
}
inline ::video_streaming::TimeRange* PROTOBUF_NONNULL BufferedRange::_internal_mutable_time_range() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_range_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::TimeRange>(GetArena());
    _impl_.time_range_ = reinterpret_cast<::video_streaming::TimeRange*>(p);
  }
  return _impl_.time_range_;
}
inline ::video_streaming::TimeRange* PROTOBUF_NONNULL BufferedRange::mutable_time_range()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::video_streaming::TimeRange* _msg = _internal_mutable_time_range();
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.time_range)
  return _msg;
}
inline void BufferedRange::set_allocated_time_range(::video_streaming::TimeRange* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.time_range_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.time_range_ = reinterpret_cast<::video_streaming::TimeRange*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.BufferedRange.time_range)
}

// optional .video_streaming.BufferedRange.UnknownMessage1 field9 = 9;
inline bool BufferedRange::has_field9() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.field9_ != nullptr);
  return value;
}
inline void BufferedRange::clear_field9() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.field9_ != nullptr) _impl_.field9_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::video_streaming::BufferedRange_UnknownMessage1& BufferedRange::_internal_field9() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::BufferedRange_UnknownMessage1* p = _impl_.field9_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::BufferedRange_UnknownMessage1&>(::video_streaming::_BufferedRange_UnknownMessage1_default_instance_);
}
inline const ::video_streaming::BufferedRange_UnknownMessage1& BufferedRange::field9() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.field9)
  return _internal_field9();
}
inline void BufferedRange::unsafe_arena_set_allocated_field9(
    ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.field9_);
  }
  _impl_.field9_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage1*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.BufferedRange.field9)
}
inline ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE BufferedRange::release_field9() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::video_streaming::BufferedRange_UnknownMessage1* released = _impl_.field9_;
  _impl_.field9_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE BufferedRange::unsafe_arena_release_field9() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.BufferedRange.field9)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::video_streaming::BufferedRange_UnknownMessage1* temp = _impl_.field9_;
  _impl_.field9_ = nullptr;
  return temp;
}
inline ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NONNULL BufferedRange::_internal_mutable_field9() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.field9_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::BufferedRange_UnknownMessage1>(GetArena());
    _impl_.field9_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage1*>(p);
  }
  return _impl_.field9_;
}
inline ::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NONNULL BufferedRange::mutable_field9()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::video_streaming::BufferedRange_UnknownMessage1* _msg = _internal_mutable_field9();
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.field9)
  return _msg;
}
inline void BufferedRange::set_allocated_field9(::video_streaming::BufferedRange_UnknownMessage1* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.field9_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.field9_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage1*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.BufferedRange.field9)
}

// optional .video_streaming.BufferedRange.UnknownMessage2 field11 = 11;
inline bool BufferedRange::has_field11() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.field11_ != nullptr);
  return value;
}
inline void BufferedRange::clear_field11() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.field11_ != nullptr) _impl_.field11_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::video_streaming::BufferedRange_UnknownMessage2& BufferedRange::_internal_field11() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::BufferedRange_UnknownMessage2* p = _impl_.field11_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::BufferedRange_UnknownMessage2&>(::video_streaming::_BufferedRange_UnknownMessage2_default_instance_);
}
inline const ::video_streaming::BufferedRange_UnknownMessage2& BufferedRange::field11() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.field11)
  return _internal_field11();
}
inline void BufferedRange::unsafe_arena_set_allocated_field11(
    ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.field11_);
  }
  _impl_.field11_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage2*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.BufferedRange.field11)
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE BufferedRange::release_field11() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::video_streaming::BufferedRange_UnknownMessage2* released = _impl_.field11_;
  _impl_.field11_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE BufferedRange::unsafe_arena_release_field11() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.BufferedRange.field11)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::video_streaming::BufferedRange_UnknownMessage2* temp = _impl_.field11_;
  _impl_.field11_ = nullptr;
  return temp;
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL BufferedRange::_internal_mutable_field11() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.field11_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::BufferedRange_UnknownMessage2>(GetArena());
    _impl_.field11_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage2*>(p);
  }
  return _impl_.field11_;
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL BufferedRange::mutable_field11()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::video_streaming::BufferedRange_UnknownMessage2* _msg = _internal_mutable_field11();
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.field11)
  return _msg;
}
inline void BufferedRange::set_allocated_field11(::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.field11_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.field11_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage2*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.BufferedRange.field11)
}

// optional .video_streaming.BufferedRange.UnknownMessage2 field12 = 12;
inline bool BufferedRange::has_field12() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.field12_ != nullptr);
  return value;
}
inline void BufferedRange::clear_field12() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.field12_ != nullptr) _impl_.field12_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::video_streaming::BufferedRange_UnknownMessage2& BufferedRange::_internal_field12() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::BufferedRange_UnknownMessage2* p = _impl_.field12_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::BufferedRange_UnknownMessage2&>(::video_streaming::_BufferedRange_UnknownMessage2_default_instance_);
}
inline const ::video_streaming::BufferedRange_UnknownMessage2& BufferedRange::field12() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.BufferedRange.field12)
  return _internal_field12();
}
inline void BufferedRange::unsafe_arena_set_allocated_field12(
    ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.field12_);
  }
  _impl_.field12_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage2*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.BufferedRange.field12)
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE BufferedRange::release_field12() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::video_streaming::BufferedRange_UnknownMessage2* released = _impl_.field12_;
  _impl_.field12_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE BufferedRange::unsafe_arena_release_field12() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.BufferedRange.field12)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::video_streaming::BufferedRange_UnknownMessage2* temp = _impl_.field12_;
  _impl_.field12_ = nullptr;
  return temp;
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL BufferedRange::_internal_mutable_field12() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.field12_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::BufferedRange_UnknownMessage2>(GetArena());
    _impl_.field12_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage2*>(p);
  }
  return _impl_.field12_;
}
inline ::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NONNULL BufferedRange::mutable_field12()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::video_streaming::BufferedRange_UnknownMessage2* _msg = _internal_mutable_field12();
  // @@protoc_insertion_point(field_mutable:video_streaming.BufferedRange.field12)
  return _msg;
}
inline void BufferedRange::set_allocated_field12(::video_streaming::BufferedRange_UnknownMessage2* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.field12_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.field12_ = reinterpret_cast<::video_streaming::BufferedRange_UnknownMessage2*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.BufferedRange.field12)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // video_5fstreaming_2fbuffered_5frange_2eproto_2epb_2eh
