// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/playback_cookie.proto
// Protobuf C++ Version: 6.33.4

#include "video_streaming/playback_cookie.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace video_streaming {

inline constexpr PlaybackCookie::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        video_fmt_{nullptr},
        audio_fmt_{nullptr},
        resolution_{0},
        field2_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlaybackCookie::PlaybackCookie(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaybackCookie_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaybackCookieDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaybackCookieDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaybackCookieDefaultTypeInternal() {}
  union {
    PlaybackCookie _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaybackCookieDefaultTypeInternal _PlaybackCookie_default_instance_;
}  // namespace video_streaming
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_video_5fstreaming_2fplayback_5fcookie_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_video_5fstreaming_2fplayback_5fcookie_2eproto = nullptr;
const ::uint32_t
    TableStruct_video_5fstreaming_2fplayback_5fcookie_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::PlaybackCookie, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::PlaybackCookie, _impl_.resolution_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::PlaybackCookie, _impl_.field2_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::PlaybackCookie, _impl_.video_fmt_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::PlaybackCookie, _impl_.audio_fmt_),
        2,
        3,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::video_streaming::PlaybackCookie)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::video_streaming::_PlaybackCookie_default_instance_._instance,
};
const char descriptor_table_protodef_video_5fstreaming_2fplayback_5fcookie_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n%video_streaming/playback_cookie.proto\022"
    "\017video_streaming\032\021misc/common.proto\"z\n\016P"
    "laybackCookie\022\022\n\nresolution\030\001 \001(\005\022\016\n\006fie"
    "ld2\030\002 \001(\005\022!\n\tvideo_fmt\030\007 \001(\0132\016.misc.Form"
    "atId\022!\n\taudio_fmt\030\010 \001(\0132\016.misc.FormatId"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto_deps[1] = {
        &::descriptor_table_misc_2fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto = {
    false,
    false,
    199,
    descriptor_table_protodef_video_5fstreaming_2fplayback_5fcookie_2eproto,
    "video_streaming/playback_cookie.proto",
    &descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto_once,
    descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_video_5fstreaming_2fplayback_5fcookie_2eproto::offsets,
    file_level_enum_descriptors_video_5fstreaming_2fplayback_5fcookie_2eproto,
    file_level_service_descriptors_video_5fstreaming_2fplayback_5fcookie_2eproto,
};
namespace video_streaming {
// ===================================================================

class PlaybackCookie::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaybackCookie>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_._has_bits_);
};

void PlaybackCookie::clear_video_fmt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.video_fmt_ != nullptr) _impl_.video_fmt_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
void PlaybackCookie::clear_audio_fmt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.audio_fmt_ != nullptr) _impl_.audio_fmt_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
PlaybackCookie::PlaybackCookie(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaybackCookie_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.PlaybackCookie)
}
PROTOBUF_NDEBUG_INLINE PlaybackCookie::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::PlaybackCookie& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

PlaybackCookie::PlaybackCookie(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaybackCookie& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaybackCookie_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaybackCookie* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.video_fmt_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.video_fmt_)
                : nullptr;
  _impl_.audio_fmt_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.audio_fmt_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, resolution_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, resolution_),
           offsetof(Impl_, field2_) -
               offsetof(Impl_, resolution_) +
               sizeof(Impl_::field2_));

  // @@protoc_insertion_point(copy_constructor:video_streaming.PlaybackCookie)
}
PROTOBUF_NDEBUG_INLINE PlaybackCookie::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PlaybackCookie::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, video_fmt_),
           0,
           offsetof(Impl_, field2_) -
               offsetof(Impl_, video_fmt_) +
               sizeof(Impl_::field2_));
}
PlaybackCookie::~PlaybackCookie() {
  // @@protoc_insertion_point(destructor:video_streaming.PlaybackCookie)
  SharedDtor(*this);
}
inline void PlaybackCookie::SharedDtor(MessageLite& self) {
  PlaybackCookie& this_ = static_cast<PlaybackCookie&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.video_fmt_;
  delete this_._impl_.audio_fmt_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaybackCookie::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaybackCookie(arena);
}
constexpr auto PlaybackCookie::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PlaybackCookie),
                                            alignof(PlaybackCookie));
}
constexpr auto PlaybackCookie::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaybackCookie_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaybackCookie::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaybackCookie>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaybackCookie::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaybackCookie>(), &PlaybackCookie::ByteSizeLong,
              &PlaybackCookie::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_._cached_size_),
          false,
      },
      &PlaybackCookie::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaybackCookie_class_data_ =
        PlaybackCookie::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaybackCookie::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaybackCookie_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaybackCookie_class_data_.tc_table);
  return PlaybackCookie_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 0, 2>
PlaybackCookie::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_._has_bits_),
    0, // no _extensions_
    8, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967100,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PlaybackCookie_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::PlaybackCookie>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .misc.FormatId audio_fmt = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 1, 1,
      PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.audio_fmt_)}},
    // optional int32 resolution = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlaybackCookie, _impl_.resolution_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.resolution_)}},
    // optional int32 field2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlaybackCookie, _impl_.field2_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.field2_)}},
    // optional .misc.FormatId video_fmt = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.video_fmt_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 resolution = 1;
    {PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.resolution_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 field2 = 2;
    {PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.field2_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .misc.FormatId video_fmt = 7;
    {PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.video_fmt_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .misc.FormatId audio_fmt = 8;
    {PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.audio_fmt_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::misc::FormatId>()},
      {::_pbi::TcParser::GetTable<::misc::FormatId>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PlaybackCookie::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.PlaybackCookie)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.video_fmt_ != nullptr);
      _impl_.video_fmt_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.audio_fmt_ != nullptr);
      _impl_.audio_fmt_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.resolution_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.field2_) -
        reinterpret_cast<char*>(&_impl_.resolution_)) + sizeof(_impl_.field2_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaybackCookie::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaybackCookie& this_ = static_cast<const PlaybackCookie&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaybackCookie::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaybackCookie& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.PlaybackCookie)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 resolution = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_resolution(), target);
  }

  // optional int32 field2 = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_field2(), target);
  }

  // optional .misc.FormatId video_fmt = 7;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.video_fmt_, this_._impl_.video_fmt_->GetCachedSize(), target,
        stream);
  }

  // optional .misc.FormatId audio_fmt = 8;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *this_._impl_.audio_fmt_, this_._impl_.audio_fmt_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.PlaybackCookie)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaybackCookie::ByteSizeLong(const MessageLite& base) {
  const PlaybackCookie& this_ = static_cast<const PlaybackCookie&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaybackCookie::ByteSizeLong() const {
  const PlaybackCookie& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.PlaybackCookie)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // optional .misc.FormatId video_fmt = 7;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.video_fmt_);
    }
    // optional .misc.FormatId audio_fmt = 8;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.audio_fmt_);
    }
    // optional int32 resolution = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_resolution());
    }
    // optional int32 field2 = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_field2());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaybackCookie::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaybackCookie*>(&to_msg);
  auto& from = static_cast<const PlaybackCookie&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.PlaybackCookie)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.video_fmt_ != nullptr);
      if (_this->_impl_.video_fmt_ == nullptr) {
        _this->_impl_.video_fmt_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.video_fmt_);
      } else {
        _this->_impl_.video_fmt_->MergeFrom(*from._impl_.video_fmt_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.audio_fmt_ != nullptr);
      if (_this->_impl_.audio_fmt_ == nullptr) {
        _this->_impl_.audio_fmt_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.audio_fmt_);
      } else {
        _this->_impl_.audio_fmt_->MergeFrom(*from._impl_.audio_fmt_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.resolution_ = from._impl_.resolution_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.field2_ = from._impl_.field2_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaybackCookie::CopyFrom(const PlaybackCookie& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.PlaybackCookie)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaybackCookie::InternalSwap(PlaybackCookie* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.field2_)
      + sizeof(PlaybackCookie::_impl_.field2_)
      - PROTOBUF_FIELD_OFFSET(PlaybackCookie, _impl_.video_fmt_)>(
          reinterpret_cast<char*>(&_impl_.video_fmt_),
          reinterpret_cast<char*>(&other->_impl_.video_fmt_));
}

::google::protobuf::Metadata PlaybackCookie::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_video_5fstreaming_2fplayback_5fcookie_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
