// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/reload_player_response.proto
// Protobuf C++ Version: 6.33.4

#ifndef video_5fstreaming_2freload_5fplayer_5fresponse_2eproto_2epb_2eh
#define video_5fstreaming_2freload_5fplayer_5fresponse_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_video_5fstreaming_2freload_5fplayer_5fresponse_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fstreaming_2freload_5fplayer_5fresponse_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_video_5fstreaming_2freload_5fplayer_5fresponse_2eproto;
}  // extern "C"
namespace video_streaming {
class ReloadPlaybackContext;
struct ReloadPlaybackContextDefaultTypeInternal;
extern ReloadPlaybackContextDefaultTypeInternal _ReloadPlaybackContext_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReloadPlaybackContext_class_data_;
class ReloadPlaybackParams;
struct ReloadPlaybackParamsDefaultTypeInternal;
extern ReloadPlaybackParamsDefaultTypeInternal _ReloadPlaybackParams_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReloadPlaybackParams_class_data_;
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace video_streaming {

// ===================================================================


// -------------------------------------------------------------------

class ReloadPlaybackParams final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.ReloadPlaybackParams) */ {
 public:
  inline ReloadPlaybackParams() : ReloadPlaybackParams(nullptr) {}
  ~ReloadPlaybackParams() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReloadPlaybackParams* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReloadPlaybackParams));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReloadPlaybackParams(::google::protobuf::internal::ConstantInitialized);

  inline ReloadPlaybackParams(const ReloadPlaybackParams& from) : ReloadPlaybackParams(nullptr, from) {}
  inline ReloadPlaybackParams(ReloadPlaybackParams&& from) noexcept
      : ReloadPlaybackParams(nullptr, ::std::move(from)) {}
  inline ReloadPlaybackParams& operator=(const ReloadPlaybackParams& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReloadPlaybackParams& operator=(ReloadPlaybackParams&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReloadPlaybackParams& default_instance() {
    return *reinterpret_cast<const ReloadPlaybackParams*>(
        &_ReloadPlaybackParams_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ReloadPlaybackParams& a, ReloadPlaybackParams& b) { a.Swap(&b); }
  inline void Swap(ReloadPlaybackParams* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReloadPlaybackParams* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReloadPlaybackParams* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReloadPlaybackParams>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReloadPlaybackParams& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReloadPlaybackParams& from) { ReloadPlaybackParams::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReloadPlaybackParams* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.ReloadPlaybackParams"; }

  explicit ReloadPlaybackParams(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReloadPlaybackParams(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReloadPlaybackParams& from);
  ReloadPlaybackParams(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReloadPlaybackParams&& from) noexcept
      : ReloadPlaybackParams(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTokenFieldNumber = 1,
  };
  // optional string token = 1;
  bool has_token() const;
  void clear_token() ;
  const ::std::string& token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_token();
  void set_allocated_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_token();

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.ReloadPlaybackParams)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReloadPlaybackParams& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr token_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2freload_5fplayer_5fresponse_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReloadPlaybackParams_class_data_;
// -------------------------------------------------------------------

class ReloadPlaybackContext final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.ReloadPlaybackContext) */ {
 public:
  inline ReloadPlaybackContext() : ReloadPlaybackContext(nullptr) {}
  ~ReloadPlaybackContext() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReloadPlaybackContext* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReloadPlaybackContext));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReloadPlaybackContext(::google::protobuf::internal::ConstantInitialized);

  inline ReloadPlaybackContext(const ReloadPlaybackContext& from) : ReloadPlaybackContext(nullptr, from) {}
  inline ReloadPlaybackContext(ReloadPlaybackContext&& from) noexcept
      : ReloadPlaybackContext(nullptr, ::std::move(from)) {}
  inline ReloadPlaybackContext& operator=(const ReloadPlaybackContext& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReloadPlaybackContext& operator=(ReloadPlaybackContext&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReloadPlaybackContext& default_instance() {
    return *reinterpret_cast<const ReloadPlaybackContext*>(
        &_ReloadPlaybackContext_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ReloadPlaybackContext& a, ReloadPlaybackContext& b) { a.Swap(&b); }
  inline void Swap(ReloadPlaybackContext* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReloadPlaybackContext* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReloadPlaybackContext* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReloadPlaybackContext>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReloadPlaybackContext& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReloadPlaybackContext& from) { ReloadPlaybackContext::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReloadPlaybackContext* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.ReloadPlaybackContext"; }

  explicit ReloadPlaybackContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReloadPlaybackContext(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReloadPlaybackContext& from);
  ReloadPlaybackContext(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReloadPlaybackContext&& from) noexcept
      : ReloadPlaybackContext(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReloadPlaybackParamsFieldNumber = 1,
  };
  // optional .video_streaming.ReloadPlaybackParams reload_playback_params = 1;
  bool has_reload_playback_params() const;
  void clear_reload_playback_params() ;
  const ::video_streaming::ReloadPlaybackParams& reload_playback_params() const;
  [[nodiscard]] ::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE release_reload_playback_params();
  ::video_streaming::ReloadPlaybackParams* PROTOBUF_NONNULL mutable_reload_playback_params();
  void set_allocated_reload_playback_params(::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_reload_playback_params(::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE value);
  ::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE unsafe_arena_release_reload_playback_params();

  private:
  const ::video_streaming::ReloadPlaybackParams& _internal_reload_playback_params() const;
  ::video_streaming::ReloadPlaybackParams* PROTOBUF_NONNULL _internal_mutable_reload_playback_params();

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.ReloadPlaybackContext)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReloadPlaybackContext& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE reload_playback_params_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2freload_5fplayer_5fresponse_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReloadPlaybackContext_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ReloadPlaybackParams

// optional string token = 1;
inline bool ReloadPlaybackParams::has_token() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void ReloadPlaybackParams::clear_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ReloadPlaybackParams::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.ReloadPlaybackParams.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ReloadPlaybackParams::set_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:video_streaming.ReloadPlaybackParams.token)
}
inline ::std::string* PROTOBUF_NONNULL ReloadPlaybackParams::mutable_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:video_streaming.ReloadPlaybackParams.token)
  return _s;
}
inline const ::std::string& ReloadPlaybackParams::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.token_.Get();
}
inline void ReloadPlaybackParams::_internal_set_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ReloadPlaybackParams::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ReloadPlaybackParams::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.ReloadPlaybackParams.token)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.token_.Set("", GetArena());
  }
  return released;
}
inline void ReloadPlaybackParams::set_allocated_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:video_streaming.ReloadPlaybackParams.token)
}

// -------------------------------------------------------------------

// ReloadPlaybackContext

// optional .video_streaming.ReloadPlaybackParams reload_playback_params = 1;
inline bool ReloadPlaybackContext::has_reload_playback_params() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.reload_playback_params_ != nullptr);
  return value;
}
inline void ReloadPlaybackContext::clear_reload_playback_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.reload_playback_params_ != nullptr) _impl_.reload_playback_params_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::video_streaming::ReloadPlaybackParams& ReloadPlaybackContext::_internal_reload_playback_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::ReloadPlaybackParams* p = _impl_.reload_playback_params_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::ReloadPlaybackParams&>(::video_streaming::_ReloadPlaybackParams_default_instance_);
}
inline const ::video_streaming::ReloadPlaybackParams& ReloadPlaybackContext::reload_playback_params() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.ReloadPlaybackContext.reload_playback_params)
  return _internal_reload_playback_params();
}
inline void ReloadPlaybackContext::unsafe_arena_set_allocated_reload_playback_params(
    ::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.reload_playback_params_);
  }
  _impl_.reload_playback_params_ = reinterpret_cast<::video_streaming::ReloadPlaybackParams*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.ReloadPlaybackContext.reload_playback_params)
}
inline ::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE ReloadPlaybackContext::release_reload_playback_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::video_streaming::ReloadPlaybackParams* released = _impl_.reload_playback_params_;
  _impl_.reload_playback_params_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE ReloadPlaybackContext::unsafe_arena_release_reload_playback_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.ReloadPlaybackContext.reload_playback_params)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::video_streaming::ReloadPlaybackParams* temp = _impl_.reload_playback_params_;
  _impl_.reload_playback_params_ = nullptr;
  return temp;
}
inline ::video_streaming::ReloadPlaybackParams* PROTOBUF_NONNULL ReloadPlaybackContext::_internal_mutable_reload_playback_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.reload_playback_params_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::ReloadPlaybackParams>(GetArena());
    _impl_.reload_playback_params_ = reinterpret_cast<::video_streaming::ReloadPlaybackParams*>(p);
  }
  return _impl_.reload_playback_params_;
}
inline ::video_streaming::ReloadPlaybackParams* PROTOBUF_NONNULL ReloadPlaybackContext::mutable_reload_playback_params()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::video_streaming::ReloadPlaybackParams* _msg = _internal_mutable_reload_playback_params();
  // @@protoc_insertion_point(field_mutable:video_streaming.ReloadPlaybackContext.reload_playback_params)
  return _msg;
}
inline void ReloadPlaybackContext::set_allocated_reload_playback_params(::video_streaming::ReloadPlaybackParams* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.reload_playback_params_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.reload_playback_params_ = reinterpret_cast<::video_streaming::ReloadPlaybackParams*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.ReloadPlaybackContext.reload_playback_params)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // video_5fstreaming_2freload_5fplayer_5fresponse_2eproto_2epb_2eh
