// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/sabr_context_update.proto
// Protobuf C++ Version: 6.33.4

#include "video_streaming/sabr_context_update.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace video_streaming {

inline constexpr SabrContextValue_ContentInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        content_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_type_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SabrContextValue_ContentInfo::SabrContextValue_ContentInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SabrContextValue_ContentInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SabrContextValue_ContentInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SabrContextValue_ContentInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SabrContextValue_ContentInfoDefaultTypeInternal() {}
  union {
    SabrContextValue_ContentInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SabrContextValue_ContentInfoDefaultTypeInternal _SabrContextValue_ContentInfo_default_instance_;

inline constexpr SabrContextUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{0},
        scope_{static_cast< ::video_streaming::SabrContextUpdate_SabrContextScope >(0)},
        send_by_default_{false},
        write_policy_{static_cast< ::video_streaming::SabrContextUpdate_SabrContextWritePolicy >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR SabrContextUpdate::SabrContextUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SabrContextUpdate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SabrContextUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SabrContextUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SabrContextUpdateDefaultTypeInternal() {}
  union {
    SabrContextUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SabrContextUpdateDefaultTypeInternal _SabrContextUpdate_default_instance_;

inline constexpr SabrContextValue_TimingInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        content_{nullptr},
        timestamp_ms_{::int64_t{0}},
        duration_ms_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SabrContextValue_TimingInfo::SabrContextValue_TimingInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SabrContextValue_TimingInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SabrContextValue_TimingInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SabrContextValue_TimingInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SabrContextValue_TimingInfoDefaultTypeInternal() {}
  union {
    SabrContextValue_TimingInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SabrContextValue_TimingInfoDefaultTypeInternal _SabrContextValue_TimingInfo_default_instance_;

inline constexpr SabrContextValue::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        signature_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timing_{nullptr},
        field5_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SabrContextValue::SabrContextValue(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SabrContextValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SabrContextValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SabrContextValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SabrContextValueDefaultTypeInternal() {}
  union {
    SabrContextValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SabrContextValueDefaultTypeInternal _SabrContextValue_default_instance_;
}  // namespace video_streaming
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto = nullptr;
const ::uint32_t
    TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextUpdate, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextUpdate, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextUpdate, _impl_.scope_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextUpdate, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextUpdate, _impl_.send_by_default_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextUpdate, _impl_.write_policy_),
        1,
        2,
        0,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_ContentInfo, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_ContentInfo, _impl_.content_id_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_ContentInfo, _impl_.content_type_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_TimingInfo, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_TimingInfo, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_TimingInfo, _impl_.duration_ms_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue_TimingInfo, _impl_.content_),
        1,
        2,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue, _impl_.timing_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue, _impl_.signature_),
        PROTOBUF_FIELD_OFFSET(::video_streaming::SabrContextValue, _impl_.field5_),
        1,
        0,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::video_streaming::SabrContextUpdate)},
        {13, sizeof(::video_streaming::SabrContextValue_ContentInfo)},
        {20, sizeof(::video_streaming::SabrContextValue_TimingInfo)},
        {29, sizeof(::video_streaming::SabrContextValue)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::video_streaming::_SabrContextUpdate_default_instance_._instance,
    &::video_streaming::_SabrContextValue_ContentInfo_default_instance_._instance,
    &::video_streaming::_SabrContextValue_TimingInfo_default_instance_._instance,
    &::video_streaming::_SabrContextValue_default_instance_._instance,
};
const char descriptor_table_protodef_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n)video_streaming/sabr_context_update.pr"
    "oto\022\017video_streaming\"\214\003\n\021SabrContextUpda"
    "te\022\014\n\004type\030\001 \001(\005\022B\n\005scope\030\002 \001(\01623.video_"
    "streaming.SabrContextUpdate.SabrContextS"
    "cope\022\r\n\005value\030\003 \001(\014\022\027\n\017send_by_default\030\004"
    " \001(\010\022O\n\014write_policy\030\005 \001(\01629.video_strea"
    "ming.SabrContextUpdate.SabrContextWriteP"
    "olicy\"_\n\020SabrContextScope\022\013\n\007UNKNOWN\020\000\022\014"
    "\n\010PLAYBACK\020\001\022\013\n\007REQUEST\020\002\022\022\n\016WATCH_ENDPO"
    "INT\020\003\022\017\n\013CONTENT_ADS\020\004\"K\n\026SabrContextWri"
    "tePolicy\022\017\n\013UNSPECIFIED\020\000\022\r\n\tOVERWRITE\020\001"
    "\022\021\n\rKEEP_EXISTING\020\002\"\245\002\n\020SabrContextValue"
    "\022<\n\006timing\030\001 \001(\0132,.video_streaming.SabrC"
    "ontextValue.TimingInfo\022\021\n\tsignature\030\002 \001("
    "\014\022\016\n\006field5\030\005 \001(\005\0327\n\013ContentInfo\022\022\n\ncont"
    "ent_id\030\001 \001(\t\022\024\n\014content_type\030\002 \001(\005\032w\n\nTi"
    "mingInfo\022\024\n\014timestamp_ms\030\001 \001(\003\022\023\n\013durati"
    "on_ms\030\002 \001(\005\022>\n\007content\030\003 \001(\0132-.video_str"
    "eaming.SabrContextValue.ContentInfo"
};
static ::absl::once_flag descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto = {
    false,
    false,
    755,
    descriptor_table_protodef_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
    "video_streaming/sabr_context_update.proto",
    &descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto::offsets,
    file_level_enum_descriptors_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
    file_level_service_descriptors_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
};
namespace video_streaming {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SabrContextUpdate_SabrContextScope_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto);
  return file_level_enum_descriptors_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t SabrContextUpdate_SabrContextScope_internal_data_[] = {
    327680u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SabrContextUpdate_SabrContextWritePolicy_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto);
  return file_level_enum_descriptors_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t SabrContextUpdate_SabrContextWritePolicy_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class SabrContextUpdate::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SabrContextUpdate>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_._has_bits_);
};

SabrContextUpdate::SabrContextUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.SabrContextUpdate)
}
PROTOBUF_NDEBUG_INLINE SabrContextUpdate::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::SabrContextUpdate& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

SabrContextUpdate::SabrContextUpdate(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SabrContextUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SabrContextUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, write_policy_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::write_policy_));

  // @@protoc_insertion_point(copy_constructor:video_streaming.SabrContextUpdate)
}
PROTOBUF_NDEBUG_INLINE SabrContextUpdate::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        value_(arena) {}

inline void SabrContextUpdate::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, write_policy_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::write_policy_));
}
SabrContextUpdate::~SabrContextUpdate() {
  // @@protoc_insertion_point(destructor:video_streaming.SabrContextUpdate)
  SharedDtor(*this);
}
inline void SabrContextUpdate::SharedDtor(MessageLite& self) {
  SabrContextUpdate& this_ = static_cast<SabrContextUpdate&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SabrContextUpdate::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SabrContextUpdate(arena);
}
constexpr auto SabrContextUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SabrContextUpdate),
                                            alignof(SabrContextUpdate));
}
constexpr auto SabrContextUpdate::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SabrContextUpdate_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SabrContextUpdate::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SabrContextUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SabrContextUpdate::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SabrContextUpdate>(), &SabrContextUpdate::ByteSizeLong,
              &SabrContextUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_._cached_size_),
          false,
      },
      &SabrContextUpdate::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SabrContextUpdate_class_data_ =
        SabrContextUpdate::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SabrContextUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SabrContextUpdate_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SabrContextUpdate_class_data_.tc_table);
  return SabrContextUpdate_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 2>
SabrContextUpdate::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SabrContextUpdate_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::SabrContextUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SabrContextUpdate, _impl_.type_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.type_)}},
    // optional .video_streaming.SabrContextUpdate.SabrContextScope scope = 2;
    {::_pbi::TcParser::FastEr0S1,
     {16, 2, 4,
      PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.scope_)}},
    // optional bytes value = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.value_)}},
    // optional bool send_by_default = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SabrContextUpdate, _impl_.send_by_default_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.send_by_default_)}},
    // optional .video_streaming.SabrContextUpdate.SabrContextWritePolicy write_policy = 5;
    {::_pbi::TcParser::FastEr0S1,
     {40, 4, 2,
      PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.write_policy_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 type = 1;
    {PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .video_streaming.SabrContextUpdate.SabrContextScope scope = 2;
    {PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.scope_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional bytes value = 3;
    {PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bool send_by_default = 4;
    {PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.send_by_default_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .video_streaming.SabrContextUpdate.SabrContextWritePolicy write_policy = 5;
    {PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.write_policy_), _Internal::kHasBitsOffset + 4, 1, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
  }},
  {{
      {0, 4},
      {0, 2},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SabrContextUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.SabrContextUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.value_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.write_policy_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.write_policy_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SabrContextUpdate::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SabrContextUpdate& this_ = static_cast<const SabrContextUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SabrContextUpdate::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SabrContextUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.SabrContextUpdate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_type(), target);
  }

  // optional .video_streaming.SabrContextUpdate.SabrContextScope scope = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_scope(), target);
  }

  // optional bytes value = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_value();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // optional bool send_by_default = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_send_by_default(), target);
  }

  // optional .video_streaming.SabrContextUpdate.SabrContextWritePolicy write_policy = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, this_._internal_write_policy(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.SabrContextUpdate)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SabrContextUpdate::ByteSizeLong(const MessageLite& base) {
  const SabrContextUpdate& this_ = static_cast<const SabrContextUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SabrContextUpdate::ByteSizeLong() const {
  const SabrContextUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.SabrContextUpdate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000008U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000017U)) {
    // optional bytes value = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_value());
    }
    // optional int32 type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_type());
    }
    // optional .video_streaming.SabrContextUpdate.SabrContextScope scope = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_scope());
    }
    // optional .video_streaming.SabrContextUpdate.SabrContextWritePolicy write_policy = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_write_policy());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SabrContextUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SabrContextUpdate*>(&to_msg);
  auto& from = static_cast<const SabrContextUpdate&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.SabrContextUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_value(from._internal_value());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.scope_ = from._impl_.scope_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.send_by_default_ = from._impl_.send_by_default_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.write_policy_ = from._impl_.write_policy_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SabrContextUpdate::CopyFrom(const SabrContextUpdate& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.SabrContextUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SabrContextUpdate::InternalSwap(SabrContextUpdate* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.write_policy_)
      + sizeof(SabrContextUpdate::_impl_.write_policy_)
      - PROTOBUF_FIELD_OFFSET(SabrContextUpdate, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata SabrContextUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SabrContextValue_ContentInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SabrContextValue_ContentInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_._has_bits_);
};

SabrContextValue_ContentInfo::SabrContextValue_ContentInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextValue_ContentInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.SabrContextValue.ContentInfo)
}
PROTOBUF_NDEBUG_INLINE SabrContextValue_ContentInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::SabrContextValue_ContentInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        content_id_(arena, from.content_id_) {}

SabrContextValue_ContentInfo::SabrContextValue_ContentInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SabrContextValue_ContentInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextValue_ContentInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SabrContextValue_ContentInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.content_type_ = from._impl_.content_type_;

  // @@protoc_insertion_point(copy_constructor:video_streaming.SabrContextValue.ContentInfo)
}
PROTOBUF_NDEBUG_INLINE SabrContextValue_ContentInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        content_id_(arena) {}

inline void SabrContextValue_ContentInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.content_type_ = {};
}
SabrContextValue_ContentInfo::~SabrContextValue_ContentInfo() {
  // @@protoc_insertion_point(destructor:video_streaming.SabrContextValue.ContentInfo)
  SharedDtor(*this);
}
inline void SabrContextValue_ContentInfo::SharedDtor(MessageLite& self) {
  SabrContextValue_ContentInfo& this_ = static_cast<SabrContextValue_ContentInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.content_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SabrContextValue_ContentInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SabrContextValue_ContentInfo(arena);
}
constexpr auto SabrContextValue_ContentInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SabrContextValue_ContentInfo),
                                            alignof(SabrContextValue_ContentInfo));
}
constexpr auto SabrContextValue_ContentInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SabrContextValue_ContentInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SabrContextValue_ContentInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SabrContextValue_ContentInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SabrContextValue_ContentInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SabrContextValue_ContentInfo>(), &SabrContextValue_ContentInfo::ByteSizeLong,
              &SabrContextValue_ContentInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_._cached_size_),
          false,
      },
      &SabrContextValue_ContentInfo::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SabrContextValue_ContentInfo_class_data_ =
        SabrContextValue_ContentInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SabrContextValue_ContentInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SabrContextValue_ContentInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SabrContextValue_ContentInfo_class_data_.tc_table);
  return SabrContextValue_ContentInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
SabrContextValue_ContentInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SabrContextValue_ContentInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::SabrContextValue_ContentInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 content_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SabrContextValue_ContentInfo, _impl_.content_type_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_.content_type_)}},
    // optional string content_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_.content_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string content_id = 1;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_.content_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 content_type = 2;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue_ContentInfo, _impl_.content_type_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SabrContextValue_ContentInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.SabrContextValue.ContentInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.content_id_.ClearNonDefaultToEmpty();
  }
  _impl_.content_type_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SabrContextValue_ContentInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SabrContextValue_ContentInfo& this_ = static_cast<const SabrContextValue_ContentInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SabrContextValue_ContentInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SabrContextValue_ContentInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.SabrContextValue.ContentInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string content_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_content_id();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional int32 content_type = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_content_type(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.SabrContextValue.ContentInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SabrContextValue_ContentInfo::ByteSizeLong(const MessageLite& base) {
  const SabrContextValue_ContentInfo& this_ = static_cast<const SabrContextValue_ContentInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SabrContextValue_ContentInfo::ByteSizeLong() const {
  const SabrContextValue_ContentInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.SabrContextValue.ContentInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string content_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_content_id());
    }
    // optional int32 content_type = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_content_type());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SabrContextValue_ContentInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SabrContextValue_ContentInfo*>(&to_msg);
  auto& from = static_cast<const SabrContextValue_ContentInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.SabrContextValue.ContentInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_content_id(from._internal_content_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.content_type_ = from._impl_.content_type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SabrContextValue_ContentInfo::CopyFrom(const SabrContextValue_ContentInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.SabrContextValue.ContentInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SabrContextValue_ContentInfo::InternalSwap(SabrContextValue_ContentInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_id_, &other->_impl_.content_id_, arena);
  swap(_impl_.content_type_, other->_impl_.content_type_);
}

::google::protobuf::Metadata SabrContextValue_ContentInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SabrContextValue_TimingInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SabrContextValue_TimingInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_._has_bits_);
};

SabrContextValue_TimingInfo::SabrContextValue_TimingInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextValue_TimingInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.SabrContextValue.TimingInfo)
}
PROTOBUF_NDEBUG_INLINE SabrContextValue_TimingInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::SabrContextValue_TimingInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SabrContextValue_TimingInfo::SabrContextValue_TimingInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SabrContextValue_TimingInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextValue_TimingInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SabrContextValue_TimingInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.content_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.content_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_ms_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, timestamp_ms_),
           offsetof(Impl_, duration_ms_) -
               offsetof(Impl_, timestamp_ms_) +
               sizeof(Impl_::duration_ms_));

  // @@protoc_insertion_point(copy_constructor:video_streaming.SabrContextValue.TimingInfo)
}
PROTOBUF_NDEBUG_INLINE SabrContextValue_TimingInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SabrContextValue_TimingInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, content_),
           0,
           offsetof(Impl_, duration_ms_) -
               offsetof(Impl_, content_) +
               sizeof(Impl_::duration_ms_));
}
SabrContextValue_TimingInfo::~SabrContextValue_TimingInfo() {
  // @@protoc_insertion_point(destructor:video_streaming.SabrContextValue.TimingInfo)
  SharedDtor(*this);
}
inline void SabrContextValue_TimingInfo::SharedDtor(MessageLite& self) {
  SabrContextValue_TimingInfo& this_ = static_cast<SabrContextValue_TimingInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.content_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SabrContextValue_TimingInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SabrContextValue_TimingInfo(arena);
}
constexpr auto SabrContextValue_TimingInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SabrContextValue_TimingInfo),
                                            alignof(SabrContextValue_TimingInfo));
}
constexpr auto SabrContextValue_TimingInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SabrContextValue_TimingInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SabrContextValue_TimingInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SabrContextValue_TimingInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SabrContextValue_TimingInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SabrContextValue_TimingInfo>(), &SabrContextValue_TimingInfo::ByteSizeLong,
              &SabrContextValue_TimingInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_._cached_size_),
          false,
      },
      &SabrContextValue_TimingInfo::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SabrContextValue_TimingInfo_class_data_ =
        SabrContextValue_TimingInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SabrContextValue_TimingInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SabrContextValue_TimingInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SabrContextValue_TimingInfo_class_data_.tc_table);
  return SabrContextValue_TimingInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2>
SabrContextValue_TimingInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SabrContextValue_TimingInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::SabrContextValue_TimingInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int64 timestamp_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SabrContextValue_TimingInfo, _impl_.timestamp_ms_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.timestamp_ms_)}},
    // optional int32 duration_ms = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SabrContextValue_TimingInfo, _impl_.duration_ms_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.duration_ms_)}},
    // optional .video_streaming.SabrContextValue.ContentInfo content = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 timestamp_ms = 1;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int32 duration_ms = 2;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.duration_ms_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .video_streaming.SabrContextValue.ContentInfo content = 3;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.content_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::video_streaming::SabrContextValue_ContentInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SabrContextValue_TimingInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.SabrContextValue.TimingInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.content_ != nullptr);
    _impl_.content_->Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.timestamp_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.duration_ms_) -
        reinterpret_cast<char*>(&_impl_.timestamp_ms_)) + sizeof(_impl_.duration_ms_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SabrContextValue_TimingInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SabrContextValue_TimingInfo& this_ = static_cast<const SabrContextValue_TimingInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SabrContextValue_TimingInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SabrContextValue_TimingInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.SabrContextValue.TimingInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 timestamp_ms = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this_._internal_timestamp_ms(), target);
  }

  // optional int32 duration_ms = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_duration_ms(), target);
  }

  // optional .video_streaming.SabrContextValue.ContentInfo content = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.content_, this_._impl_.content_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.SabrContextValue.TimingInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SabrContextValue_TimingInfo::ByteSizeLong(const MessageLite& base) {
  const SabrContextValue_TimingInfo& this_ = static_cast<const SabrContextValue_TimingInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SabrContextValue_TimingInfo::ByteSizeLong() const {
  const SabrContextValue_TimingInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.SabrContextValue.TimingInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional .video_streaming.SabrContextValue.ContentInfo content = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.content_);
    }
    // optional int64 timestamp_ms = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_timestamp_ms());
    }
    // optional int32 duration_ms = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_duration_ms());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SabrContextValue_TimingInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SabrContextValue_TimingInfo*>(&to_msg);
  auto& from = static_cast<const SabrContextValue_TimingInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.SabrContextValue.TimingInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.content_ != nullptr);
      if (_this->_impl_.content_ == nullptr) {
        _this->_impl_.content_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.content_);
      } else {
        _this->_impl_.content_->MergeFrom(*from._impl_.content_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.duration_ms_ = from._impl_.duration_ms_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SabrContextValue_TimingInfo::CopyFrom(const SabrContextValue_TimingInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.SabrContextValue.TimingInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SabrContextValue_TimingInfo::InternalSwap(SabrContextValue_TimingInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.duration_ms_)
      + sizeof(SabrContextValue_TimingInfo::_impl_.duration_ms_)
      - PROTOBUF_FIELD_OFFSET(SabrContextValue_TimingInfo, _impl_.content_)>(
          reinterpret_cast<char*>(&_impl_.content_),
          reinterpret_cast<char*>(&other->_impl_.content_));
}

::google::protobuf::Metadata SabrContextValue_TimingInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SabrContextValue::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SabrContextValue>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_._has_bits_);
};

SabrContextValue::SabrContextValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:video_streaming.SabrContextValue)
}
PROTOBUF_NDEBUG_INLINE SabrContextValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::video_streaming::SabrContextValue& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        signature_(arena, from.signature_) {}

SabrContextValue::SabrContextValue(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SabrContextValue& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SabrContextValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SabrContextValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.timing_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.timing_)
                : nullptr;
  _impl_.field5_ = from._impl_.field5_;

  // @@protoc_insertion_point(copy_constructor:video_streaming.SabrContextValue)
}
PROTOBUF_NDEBUG_INLINE SabrContextValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        signature_(arena) {}

inline void SabrContextValue::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timing_),
           0,
           offsetof(Impl_, field5_) -
               offsetof(Impl_, timing_) +
               sizeof(Impl_::field5_));
}
SabrContextValue::~SabrContextValue() {
  // @@protoc_insertion_point(destructor:video_streaming.SabrContextValue)
  SharedDtor(*this);
}
inline void SabrContextValue::SharedDtor(MessageLite& self) {
  SabrContextValue& this_ = static_cast<SabrContextValue&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.signature_.Destroy();
  delete this_._impl_.timing_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SabrContextValue::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SabrContextValue(arena);
}
constexpr auto SabrContextValue::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SabrContextValue),
                                            alignof(SabrContextValue));
}
constexpr auto SabrContextValue::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SabrContextValue_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SabrContextValue::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SabrContextValue>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SabrContextValue::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SabrContextValue>(), &SabrContextValue::ByteSizeLong,
              &SabrContextValue::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_._cached_size_),
          false,
      },
      &SabrContextValue::kDescriptorMethods,
      &descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SabrContextValue_class_data_ =
        SabrContextValue::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SabrContextValue::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SabrContextValue_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SabrContextValue_class_data_.tc_table);
  return SabrContextValue_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 3, 1, 0, 2>
SabrContextValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_._has_bits_),
    0, // no _extensions_
    5, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967276,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SabrContextValue_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::video_streaming::SabrContextValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes signature = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.signature_)}},
    // optional .video_streaming.SabrContextValue.TimingInfo timing = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.timing_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .video_streaming.SabrContextValue.TimingInfo timing = 1;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.timing_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bytes signature = 2;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.signature_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 field5 = 5;
    {PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.field5_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::video_streaming::SabrContextValue_TimingInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SabrContextValue::Clear() {
// @@protoc_insertion_point(message_clear_start:video_streaming.SabrContextValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.signature_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.timing_ != nullptr);
      _impl_.timing_->Clear();
    }
  }
  _impl_.field5_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SabrContextValue::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SabrContextValue& this_ = static_cast<const SabrContextValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SabrContextValue::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SabrContextValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:video_streaming.SabrContextValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .video_streaming.SabrContextValue.TimingInfo timing = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.timing_, this_._impl_.timing_->GetCachedSize(), target,
        stream);
  }

  // optional bytes signature = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_signature();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional int32 field5 = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_field5(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:video_streaming.SabrContextValue)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SabrContextValue::ByteSizeLong(const MessageLite& base) {
  const SabrContextValue& this_ = static_cast<const SabrContextValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SabrContextValue::ByteSizeLong() const {
  const SabrContextValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:video_streaming.SabrContextValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional bytes signature = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_signature());
    }
    // optional .video_streaming.SabrContextValue.TimingInfo timing = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timing_);
    }
    // optional int32 field5 = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_field5());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SabrContextValue::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SabrContextValue*>(&to_msg);
  auto& from = static_cast<const SabrContextValue&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:video_streaming.SabrContextValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_signature(from._internal_signature());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.timing_ != nullptr);
      if (_this->_impl_.timing_ == nullptr) {
        _this->_impl_.timing_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.timing_);
      } else {
        _this->_impl_.timing_->MergeFrom(*from._impl_.timing_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.field5_ = from._impl_.field5_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SabrContextValue::CopyFrom(const SabrContextValue& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:video_streaming.SabrContextValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SabrContextValue::InternalSwap(SabrContextValue* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.signature_, &other->_impl_.signature_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.field5_)
      + sizeof(SabrContextValue::_impl_.field5_)
      - PROTOBUF_FIELD_OFFSET(SabrContextValue, _impl_.timing_)>(
          reinterpret_cast<char*>(&_impl_.timing_),
          reinterpret_cast<char*>(&other->_impl_.timing_));
}

::google::protobuf::Metadata SabrContextValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
