// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/sabr_context_update.proto
// Protobuf C++ Version: 6.33.4

#ifndef video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto_2epb_2eh
#define video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto;
}  // extern "C"
namespace video_streaming {
enum SabrContextUpdate_SabrContextScope : int;
extern const uint32_t SabrContextUpdate_SabrContextScope_internal_data_[];
enum SabrContextUpdate_SabrContextWritePolicy : int;
extern const uint32_t SabrContextUpdate_SabrContextWritePolicy_internal_data_[];
class SabrContextUpdate;
struct SabrContextUpdateDefaultTypeInternal;
extern SabrContextUpdateDefaultTypeInternal _SabrContextUpdate_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SabrContextUpdate_class_data_;
class SabrContextValue;
struct SabrContextValueDefaultTypeInternal;
extern SabrContextValueDefaultTypeInternal _SabrContextValue_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SabrContextValue_class_data_;
class SabrContextValue_ContentInfo;
struct SabrContextValue_ContentInfoDefaultTypeInternal;
extern SabrContextValue_ContentInfoDefaultTypeInternal _SabrContextValue_ContentInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SabrContextValue_ContentInfo_class_data_;
class SabrContextValue_TimingInfo;
struct SabrContextValue_TimingInfoDefaultTypeInternal;
extern SabrContextValue_TimingInfoDefaultTypeInternal _SabrContextValue_TimingInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SabrContextValue_TimingInfo_class_data_;
}  // namespace video_streaming
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::video_streaming::SabrContextUpdate_SabrContextScope_internal_data_>
    internal::EnumTraitsImpl::value<::video_streaming::SabrContextUpdate_SabrContextScope>;
template <>
internal::EnumTraitsT<::video_streaming::SabrContextUpdate_SabrContextWritePolicy_internal_data_>
    internal::EnumTraitsImpl::value<::video_streaming::SabrContextUpdate_SabrContextWritePolicy>;
}  // namespace protobuf
}  // namespace google

namespace video_streaming {
enum SabrContextUpdate_SabrContextScope : int {
  SabrContextUpdate_SabrContextScope_UNKNOWN = 0,
  SabrContextUpdate_SabrContextScope_PLAYBACK = 1,
  SabrContextUpdate_SabrContextScope_REQUEST = 2,
  SabrContextUpdate_SabrContextScope_WATCH_ENDPOINT = 3,
  SabrContextUpdate_SabrContextScope_CONTENT_ADS = 4,
};

extern const uint32_t SabrContextUpdate_SabrContextScope_internal_data_[];
inline constexpr SabrContextUpdate_SabrContextScope SabrContextUpdate_SabrContextScope_SabrContextScope_MIN =
    static_cast<SabrContextUpdate_SabrContextScope>(0);
inline constexpr SabrContextUpdate_SabrContextScope SabrContextUpdate_SabrContextScope_SabrContextScope_MAX =
    static_cast<SabrContextUpdate_SabrContextScope>(4);
inline bool SabrContextUpdate_SabrContextScope_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int SabrContextUpdate_SabrContextScope_SabrContextScope_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SabrContextUpdate_SabrContextScope_descriptor();
template <typename T>
const ::std::string& SabrContextUpdate_SabrContextScope_Name(T value) {
  static_assert(::std::is_same<T, SabrContextUpdate_SabrContextScope>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to SabrContextScope_Name().");
  return SabrContextUpdate_SabrContextScope_Name(static_cast<SabrContextUpdate_SabrContextScope>(value));
}
template <>
inline const ::std::string& SabrContextUpdate_SabrContextScope_Name(SabrContextUpdate_SabrContextScope value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SabrContextUpdate_SabrContextScope_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool SabrContextUpdate_SabrContextScope_Parse(
    ::absl::string_view name, SabrContextUpdate_SabrContextScope* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<SabrContextUpdate_SabrContextScope>(SabrContextUpdate_SabrContextScope_descriptor(), name,
                                           value);
}
enum SabrContextUpdate_SabrContextWritePolicy : int {
  SabrContextUpdate_SabrContextWritePolicy_UNSPECIFIED = 0,
  SabrContextUpdate_SabrContextWritePolicy_OVERWRITE = 1,
  SabrContextUpdate_SabrContextWritePolicy_KEEP_EXISTING = 2,
};

extern const uint32_t SabrContextUpdate_SabrContextWritePolicy_internal_data_[];
inline constexpr SabrContextUpdate_SabrContextWritePolicy SabrContextUpdate_SabrContextWritePolicy_SabrContextWritePolicy_MIN =
    static_cast<SabrContextUpdate_SabrContextWritePolicy>(0);
inline constexpr SabrContextUpdate_SabrContextWritePolicy SabrContextUpdate_SabrContextWritePolicy_SabrContextWritePolicy_MAX =
    static_cast<SabrContextUpdate_SabrContextWritePolicy>(2);
inline bool SabrContextUpdate_SabrContextWritePolicy_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int SabrContextUpdate_SabrContextWritePolicy_SabrContextWritePolicy_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SabrContextUpdate_SabrContextWritePolicy_descriptor();
template <typename T>
const ::std::string& SabrContextUpdate_SabrContextWritePolicy_Name(T value) {
  static_assert(::std::is_same<T, SabrContextUpdate_SabrContextWritePolicy>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to SabrContextWritePolicy_Name().");
  return SabrContextUpdate_SabrContextWritePolicy_Name(static_cast<SabrContextUpdate_SabrContextWritePolicy>(value));
}
template <>
inline const ::std::string& SabrContextUpdate_SabrContextWritePolicy_Name(SabrContextUpdate_SabrContextWritePolicy value) {
  return ::google::protobuf::internal::NameOfDenseEnum<SabrContextUpdate_SabrContextWritePolicy_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool SabrContextUpdate_SabrContextWritePolicy_Parse(
    ::absl::string_view name, SabrContextUpdate_SabrContextWritePolicy* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<SabrContextUpdate_SabrContextWritePolicy>(SabrContextUpdate_SabrContextWritePolicy_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SabrContextValue_ContentInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.SabrContextValue.ContentInfo) */ {
 public:
  inline SabrContextValue_ContentInfo() : SabrContextValue_ContentInfo(nullptr) {}
  ~SabrContextValue_ContentInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SabrContextValue_ContentInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SabrContextValue_ContentInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SabrContextValue_ContentInfo(::google::protobuf::internal::ConstantInitialized);

  inline SabrContextValue_ContentInfo(const SabrContextValue_ContentInfo& from) : SabrContextValue_ContentInfo(nullptr, from) {}
  inline SabrContextValue_ContentInfo(SabrContextValue_ContentInfo&& from) noexcept
      : SabrContextValue_ContentInfo(nullptr, ::std::move(from)) {}
  inline SabrContextValue_ContentInfo& operator=(const SabrContextValue_ContentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SabrContextValue_ContentInfo& operator=(SabrContextValue_ContentInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SabrContextValue_ContentInfo& default_instance() {
    return *reinterpret_cast<const SabrContextValue_ContentInfo*>(
        &_SabrContextValue_ContentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SabrContextValue_ContentInfo& a, SabrContextValue_ContentInfo& b) { a.Swap(&b); }
  inline void Swap(SabrContextValue_ContentInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SabrContextValue_ContentInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SabrContextValue_ContentInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SabrContextValue_ContentInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SabrContextValue_ContentInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SabrContextValue_ContentInfo& from) { SabrContextValue_ContentInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SabrContextValue_ContentInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.SabrContextValue.ContentInfo"; }

  explicit SabrContextValue_ContentInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SabrContextValue_ContentInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SabrContextValue_ContentInfo& from);
  SabrContextValue_ContentInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SabrContextValue_ContentInfo&& from) noexcept
      : SabrContextValue_ContentInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContentIdFieldNumber = 1,
    kContentTypeFieldNumber = 2,
  };
  // optional string content_id = 1;
  bool has_content_id() const;
  void clear_content_id() ;
  const ::std::string& content_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_content_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_content_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_content_id();
  void set_allocated_content_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_content_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_content_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_content_id();

  public:
  // optional int32 content_type = 2;
  bool has_content_type() const;
  void clear_content_type() ;
  ::int32_t content_type() const;
  void set_content_type(::int32_t value);

  private:
  ::int32_t _internal_content_type() const;
  void _internal_set_content_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.SabrContextValue.ContentInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SabrContextValue_ContentInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr content_id_;
    ::int32_t content_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SabrContextValue_ContentInfo_class_data_;
// -------------------------------------------------------------------

class SabrContextUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.SabrContextUpdate) */ {
 public:
  inline SabrContextUpdate() : SabrContextUpdate(nullptr) {}
  ~SabrContextUpdate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SabrContextUpdate* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SabrContextUpdate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SabrContextUpdate(::google::protobuf::internal::ConstantInitialized);

  inline SabrContextUpdate(const SabrContextUpdate& from) : SabrContextUpdate(nullptr, from) {}
  inline SabrContextUpdate(SabrContextUpdate&& from) noexcept
      : SabrContextUpdate(nullptr, ::std::move(from)) {}
  inline SabrContextUpdate& operator=(const SabrContextUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline SabrContextUpdate& operator=(SabrContextUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SabrContextUpdate& default_instance() {
    return *reinterpret_cast<const SabrContextUpdate*>(
        &_SabrContextUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SabrContextUpdate& a, SabrContextUpdate& b) { a.Swap(&b); }
  inline void Swap(SabrContextUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SabrContextUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SabrContextUpdate* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SabrContextUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SabrContextUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SabrContextUpdate& from) { SabrContextUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SabrContextUpdate* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.SabrContextUpdate"; }

  explicit SabrContextUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SabrContextUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SabrContextUpdate& from);
  SabrContextUpdate(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SabrContextUpdate&& from) noexcept
      : SabrContextUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using SabrContextScope = SabrContextUpdate_SabrContextScope;
  static constexpr SabrContextScope UNKNOWN = SabrContextUpdate_SabrContextScope_UNKNOWN;
  static constexpr SabrContextScope PLAYBACK = SabrContextUpdate_SabrContextScope_PLAYBACK;
  static constexpr SabrContextScope REQUEST = SabrContextUpdate_SabrContextScope_REQUEST;
  static constexpr SabrContextScope WATCH_ENDPOINT = SabrContextUpdate_SabrContextScope_WATCH_ENDPOINT;
  static constexpr SabrContextScope CONTENT_ADS = SabrContextUpdate_SabrContextScope_CONTENT_ADS;
  static inline bool SabrContextScope_IsValid(int value) {
    return SabrContextUpdate_SabrContextScope_IsValid(value);
  }
  static constexpr SabrContextScope SabrContextScope_MIN = SabrContextUpdate_SabrContextScope_SabrContextScope_MIN;
  static constexpr SabrContextScope SabrContextScope_MAX = SabrContextUpdate_SabrContextScope_SabrContextScope_MAX;
  static constexpr int SabrContextScope_ARRAYSIZE = SabrContextUpdate_SabrContextScope_SabrContextScope_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SabrContextScope_descriptor() {
    return SabrContextUpdate_SabrContextScope_descriptor();
  }
  template <typename T>
  static inline const ::std::string& SabrContextScope_Name(T value) {
    return SabrContextUpdate_SabrContextScope_Name(value);
  }
  static inline bool SabrContextScope_Parse(
      ::absl::string_view name, SabrContextScope* PROTOBUF_NONNULL value) {
    return SabrContextUpdate_SabrContextScope_Parse(name, value);
  }
  using SabrContextWritePolicy = SabrContextUpdate_SabrContextWritePolicy;
  static constexpr SabrContextWritePolicy UNSPECIFIED = SabrContextUpdate_SabrContextWritePolicy_UNSPECIFIED;
  static constexpr SabrContextWritePolicy OVERWRITE = SabrContextUpdate_SabrContextWritePolicy_OVERWRITE;
  static constexpr SabrContextWritePolicy KEEP_EXISTING = SabrContextUpdate_SabrContextWritePolicy_KEEP_EXISTING;
  static inline bool SabrContextWritePolicy_IsValid(int value) {
    return SabrContextUpdate_SabrContextWritePolicy_IsValid(value);
  }
  static constexpr SabrContextWritePolicy SabrContextWritePolicy_MIN = SabrContextUpdate_SabrContextWritePolicy_SabrContextWritePolicy_MIN;
  static constexpr SabrContextWritePolicy SabrContextWritePolicy_MAX = SabrContextUpdate_SabrContextWritePolicy_SabrContextWritePolicy_MAX;
  static constexpr int SabrContextWritePolicy_ARRAYSIZE = SabrContextUpdate_SabrContextWritePolicy_SabrContextWritePolicy_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL SabrContextWritePolicy_descriptor() {
    return SabrContextUpdate_SabrContextWritePolicy_descriptor();
  }
  template <typename T>
  static inline const ::std::string& SabrContextWritePolicy_Name(T value) {
    return SabrContextUpdate_SabrContextWritePolicy_Name(value);
  }
  static inline bool SabrContextWritePolicy_Parse(
      ::absl::string_view name, SabrContextWritePolicy* PROTOBUF_NONNULL value) {
    return SabrContextUpdate_SabrContextWritePolicy_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 3,
    kTypeFieldNumber = 1,
    kScopeFieldNumber = 2,
    kSendByDefaultFieldNumber = 4,
    kWritePolicyFieldNumber = 5,
  };
  // optional bytes value = 3;
  bool has_value() const;
  void clear_value() ;
  const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // optional int32 type = 1;
  bool has_type() const;
  void clear_type() ;
  ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // optional .video_streaming.SabrContextUpdate.SabrContextScope scope = 2;
  bool has_scope() const;
  void clear_scope() ;
  ::video_streaming::SabrContextUpdate_SabrContextScope scope() const;
  void set_scope(::video_streaming::SabrContextUpdate_SabrContextScope value);

  private:
  ::video_streaming::SabrContextUpdate_SabrContextScope _internal_scope() const;
  void _internal_set_scope(::video_streaming::SabrContextUpdate_SabrContextScope value);

  public:
  // optional bool send_by_default = 4;
  bool has_send_by_default() const;
  void clear_send_by_default() ;
  bool send_by_default() const;
  void set_send_by_default(bool value);

  private:
  bool _internal_send_by_default() const;
  void _internal_set_send_by_default(bool value);

  public:
  // optional .video_streaming.SabrContextUpdate.SabrContextWritePolicy write_policy = 5;
  bool has_write_policy() const;
  void clear_write_policy() ;
  ::video_streaming::SabrContextUpdate_SabrContextWritePolicy write_policy() const;
  void set_write_policy(::video_streaming::SabrContextUpdate_SabrContextWritePolicy value);

  private:
  ::video_streaming::SabrContextUpdate_SabrContextWritePolicy _internal_write_policy() const;
  void _internal_set_write_policy(::video_streaming::SabrContextUpdate_SabrContextWritePolicy value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.SabrContextUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SabrContextUpdate& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    ::int32_t type_;
    int scope_;
    bool send_by_default_;
    int write_policy_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SabrContextUpdate_class_data_;
// -------------------------------------------------------------------

class SabrContextValue_TimingInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.SabrContextValue.TimingInfo) */ {
 public:
  inline SabrContextValue_TimingInfo() : SabrContextValue_TimingInfo(nullptr) {}
  ~SabrContextValue_TimingInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SabrContextValue_TimingInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SabrContextValue_TimingInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SabrContextValue_TimingInfo(::google::protobuf::internal::ConstantInitialized);

  inline SabrContextValue_TimingInfo(const SabrContextValue_TimingInfo& from) : SabrContextValue_TimingInfo(nullptr, from) {}
  inline SabrContextValue_TimingInfo(SabrContextValue_TimingInfo&& from) noexcept
      : SabrContextValue_TimingInfo(nullptr, ::std::move(from)) {}
  inline SabrContextValue_TimingInfo& operator=(const SabrContextValue_TimingInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline SabrContextValue_TimingInfo& operator=(SabrContextValue_TimingInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SabrContextValue_TimingInfo& default_instance() {
    return *reinterpret_cast<const SabrContextValue_TimingInfo*>(
        &_SabrContextValue_TimingInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SabrContextValue_TimingInfo& a, SabrContextValue_TimingInfo& b) { a.Swap(&b); }
  inline void Swap(SabrContextValue_TimingInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SabrContextValue_TimingInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SabrContextValue_TimingInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SabrContextValue_TimingInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SabrContextValue_TimingInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SabrContextValue_TimingInfo& from) { SabrContextValue_TimingInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SabrContextValue_TimingInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.SabrContextValue.TimingInfo"; }

  explicit SabrContextValue_TimingInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SabrContextValue_TimingInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SabrContextValue_TimingInfo& from);
  SabrContextValue_TimingInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SabrContextValue_TimingInfo&& from) noexcept
      : SabrContextValue_TimingInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContentFieldNumber = 3,
    kTimestampMsFieldNumber = 1,
    kDurationMsFieldNumber = 2,
  };
  // optional .video_streaming.SabrContextValue.ContentInfo content = 3;
  bool has_content() const;
  void clear_content() ;
  const ::video_streaming::SabrContextValue_ContentInfo& content() const;
  [[nodiscard]] ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE release_content();
  ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NONNULL mutable_content();
  void set_allocated_content(::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_content(::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE value);
  ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE unsafe_arena_release_content();

  private:
  const ::video_streaming::SabrContextValue_ContentInfo& _internal_content() const;
  ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NONNULL _internal_mutable_content();

  public:
  // optional int64 timestamp_ms = 1;
  bool has_timestamp_ms() const;
  void clear_timestamp_ms() ;
  ::int64_t timestamp_ms() const;
  void set_timestamp_ms(::int64_t value);

  private:
  ::int64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::int64_t value);

  public:
  // optional int32 duration_ms = 2;
  bool has_duration_ms() const;
  void clear_duration_ms() ;
  ::int32_t duration_ms() const;
  void set_duration_ms(::int32_t value);

  private:
  ::int32_t _internal_duration_ms() const;
  void _internal_set_duration_ms(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.SabrContextValue.TimingInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SabrContextValue_TimingInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE content_;
    ::int64_t timestamp_ms_;
    ::int32_t duration_ms_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SabrContextValue_TimingInfo_class_data_;
// -------------------------------------------------------------------

class SabrContextValue final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.SabrContextValue) */ {
 public:
  inline SabrContextValue() : SabrContextValue(nullptr) {}
  ~SabrContextValue() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SabrContextValue* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SabrContextValue));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SabrContextValue(::google::protobuf::internal::ConstantInitialized);

  inline SabrContextValue(const SabrContextValue& from) : SabrContextValue(nullptr, from) {}
  inline SabrContextValue(SabrContextValue&& from) noexcept
      : SabrContextValue(nullptr, ::std::move(from)) {}
  inline SabrContextValue& operator=(const SabrContextValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline SabrContextValue& operator=(SabrContextValue&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SabrContextValue& default_instance() {
    return *reinterpret_cast<const SabrContextValue*>(
        &_SabrContextValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SabrContextValue& a, SabrContextValue& b) { a.Swap(&b); }
  inline void Swap(SabrContextValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SabrContextValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SabrContextValue* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SabrContextValue>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SabrContextValue& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SabrContextValue& from) { SabrContextValue::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SabrContextValue* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.SabrContextValue"; }

  explicit SabrContextValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SabrContextValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SabrContextValue& from);
  SabrContextValue(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SabrContextValue&& from) noexcept
      : SabrContextValue(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ContentInfo = SabrContextValue_ContentInfo;
  using TimingInfo = SabrContextValue_TimingInfo;

  // accessors -------------------------------------------------------
  enum : int {
    kSignatureFieldNumber = 2,
    kTimingFieldNumber = 1,
    kField5FieldNumber = 5,
  };
  // optional bytes signature = 2;
  bool has_signature() const;
  void clear_signature() ;
  const ::std::string& signature() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_signature(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_signature();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_signature();
  void set_allocated_signature(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_signature() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_signature();

  public:
  // optional .video_streaming.SabrContextValue.TimingInfo timing = 1;
  bool has_timing() const;
  void clear_timing() ;
  const ::video_streaming::SabrContextValue_TimingInfo& timing() const;
  [[nodiscard]] ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE release_timing();
  ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NONNULL mutable_timing();
  void set_allocated_timing(::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timing(::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE value);
  ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE unsafe_arena_release_timing();

  private:
  const ::video_streaming::SabrContextValue_TimingInfo& _internal_timing() const;
  ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NONNULL _internal_mutable_timing();

  public:
  // optional int32 field5 = 5;
  bool has_field5() const;
  void clear_field5() ;
  ::int32_t field5() const;
  void set_field5(::int32_t value);

  private:
  ::int32_t _internal_field5() const;
  void _internal_set_field5(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.SabrContextValue)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SabrContextValue& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr signature_;
    ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE timing_;
    ::int32_t field5_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SabrContextValue_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SabrContextUpdate

// optional int32 type = 1;
inline bool SabrContextUpdate::has_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void SabrContextUpdate::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SabrContextUpdate::type() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextUpdate.type)
  return _internal_type();
}
inline void SabrContextUpdate::set_type(::int32_t value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextUpdate.type)
}
inline ::int32_t SabrContextUpdate::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void SabrContextUpdate::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// optional .video_streaming.SabrContextUpdate.SabrContextScope scope = 2;
inline bool SabrContextUpdate::has_scope() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void SabrContextUpdate::clear_scope() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scope_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::video_streaming::SabrContextUpdate_SabrContextScope SabrContextUpdate::scope() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextUpdate.scope)
  return _internal_scope();
}
inline void SabrContextUpdate::set_scope(::video_streaming::SabrContextUpdate_SabrContextScope value) {
  _internal_set_scope(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextUpdate.scope)
}
inline ::video_streaming::SabrContextUpdate_SabrContextScope SabrContextUpdate::_internal_scope() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::video_streaming::SabrContextUpdate_SabrContextScope>(_impl_.scope_);
}
inline void SabrContextUpdate::_internal_set_scope(::video_streaming::SabrContextUpdate_SabrContextScope value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::video_streaming::SabrContextUpdate_SabrContextScope_internal_data_));
                                          _impl_.scope_ = value;
}

// optional bytes value = 3;
inline bool SabrContextUpdate::has_value() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void SabrContextUpdate::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SabrContextUpdate::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextUpdate.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SabrContextUpdate::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextUpdate.value)
}
inline ::std::string* PROTOBUF_NONNULL SabrContextUpdate::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:video_streaming.SabrContextUpdate.value)
  return _s;
}
inline const ::std::string& SabrContextUpdate::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void SabrContextUpdate::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SabrContextUpdate::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SabrContextUpdate::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.SabrContextUpdate.value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void SabrContextUpdate::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:video_streaming.SabrContextUpdate.value)
}

// optional bool send_by_default = 4;
inline bool SabrContextUpdate::has_send_by_default() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void SabrContextUpdate::clear_send_by_default() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.send_by_default_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool SabrContextUpdate::send_by_default() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextUpdate.send_by_default)
  return _internal_send_by_default();
}
inline void SabrContextUpdate::set_send_by_default(bool value) {
  _internal_set_send_by_default(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextUpdate.send_by_default)
}
inline bool SabrContextUpdate::_internal_send_by_default() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.send_by_default_;
}
inline void SabrContextUpdate::_internal_set_send_by_default(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.send_by_default_ = value;
}

// optional .video_streaming.SabrContextUpdate.SabrContextWritePolicy write_policy = 5;
inline bool SabrContextUpdate::has_write_policy() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void SabrContextUpdate::clear_write_policy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.write_policy_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::video_streaming::SabrContextUpdate_SabrContextWritePolicy SabrContextUpdate::write_policy() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextUpdate.write_policy)
  return _internal_write_policy();
}
inline void SabrContextUpdate::set_write_policy(::video_streaming::SabrContextUpdate_SabrContextWritePolicy value) {
  _internal_set_write_policy(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextUpdate.write_policy)
}
inline ::video_streaming::SabrContextUpdate_SabrContextWritePolicy SabrContextUpdate::_internal_write_policy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::video_streaming::SabrContextUpdate_SabrContextWritePolicy>(_impl_.write_policy_);
}
inline void SabrContextUpdate::_internal_set_write_policy(::video_streaming::SabrContextUpdate_SabrContextWritePolicy value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::video_streaming::SabrContextUpdate_SabrContextWritePolicy_internal_data_));
                                          _impl_.write_policy_ = value;
}

// -------------------------------------------------------------------

// SabrContextValue_ContentInfo

// optional string content_id = 1;
inline bool SabrContextValue_ContentInfo::has_content_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void SabrContextValue_ContentInfo::clear_content_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SabrContextValue_ContentInfo::content_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.ContentInfo.content_id)
  return _internal_content_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SabrContextValue_ContentInfo::set_content_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.content_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextValue.ContentInfo.content_id)
}
inline ::std::string* PROTOBUF_NONNULL SabrContextValue_ContentInfo::mutable_content_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_content_id();
  // @@protoc_insertion_point(field_mutable:video_streaming.SabrContextValue.ContentInfo.content_id)
  return _s;
}
inline const ::std::string& SabrContextValue_ContentInfo::_internal_content_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_id_.Get();
}
inline void SabrContextValue_ContentInfo::_internal_set_content_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SabrContextValue_ContentInfo::_internal_mutable_content_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.content_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SabrContextValue_ContentInfo::release_content_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.SabrContextValue.ContentInfo.content_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.content_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.content_id_.Set("", GetArena());
  }
  return released;
}
inline void SabrContextValue_ContentInfo::set_allocated_content_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.content_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.content_id_.IsDefault()) {
    _impl_.content_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:video_streaming.SabrContextValue.ContentInfo.content_id)
}

// optional int32 content_type = 2;
inline bool SabrContextValue_ContentInfo::has_content_type() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void SabrContextValue_ContentInfo::clear_content_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SabrContextValue_ContentInfo::content_type() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.ContentInfo.content_type)
  return _internal_content_type();
}
inline void SabrContextValue_ContentInfo::set_content_type(::int32_t value) {
  _internal_set_content_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextValue.ContentInfo.content_type)
}
inline ::int32_t SabrContextValue_ContentInfo::_internal_content_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_type_;
}
inline void SabrContextValue_ContentInfo::_internal_set_content_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_type_ = value;
}

// -------------------------------------------------------------------

// SabrContextValue_TimingInfo

// optional int64 timestamp_ms = 1;
inline bool SabrContextValue_TimingInfo::has_timestamp_ms() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void SabrContextValue_TimingInfo::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t SabrContextValue_TimingInfo::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.TimingInfo.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void SabrContextValue_TimingInfo::set_timestamp_ms(::int64_t value) {
  _internal_set_timestamp_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextValue.TimingInfo.timestamp_ms)
}
inline ::int64_t SabrContextValue_TimingInfo::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void SabrContextValue_TimingInfo::_internal_set_timestamp_ms(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// optional int32 duration_ms = 2;
inline bool SabrContextValue_TimingInfo::has_duration_ms() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void SabrContextValue_TimingInfo::clear_duration_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_ms_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t SabrContextValue_TimingInfo::duration_ms() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.TimingInfo.duration_ms)
  return _internal_duration_ms();
}
inline void SabrContextValue_TimingInfo::set_duration_ms(::int32_t value) {
  _internal_set_duration_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextValue.TimingInfo.duration_ms)
}
inline ::int32_t SabrContextValue_TimingInfo::_internal_duration_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.duration_ms_;
}
inline void SabrContextValue_TimingInfo::_internal_set_duration_ms(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_ms_ = value;
}

// optional .video_streaming.SabrContextValue.ContentInfo content = 3;
inline bool SabrContextValue_TimingInfo::has_content() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.content_ != nullptr);
  return value;
}
inline void SabrContextValue_TimingInfo::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ != nullptr) _impl_.content_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::video_streaming::SabrContextValue_ContentInfo& SabrContextValue_TimingInfo::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::SabrContextValue_ContentInfo* p = _impl_.content_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::SabrContextValue_ContentInfo&>(::video_streaming::_SabrContextValue_ContentInfo_default_instance_);
}
inline const ::video_streaming::SabrContextValue_ContentInfo& SabrContextValue_TimingInfo::content() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.TimingInfo.content)
  return _internal_content();
}
inline void SabrContextValue_TimingInfo::unsafe_arena_set_allocated_content(
    ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }
  _impl_.content_ = reinterpret_cast<::video_streaming::SabrContextValue_ContentInfo*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.SabrContextValue.TimingInfo.content)
}
inline ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE SabrContextValue_TimingInfo::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::video_streaming::SabrContextValue_ContentInfo* released = _impl_.content_;
  _impl_.content_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE SabrContextValue_TimingInfo::unsafe_arena_release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.SabrContextValue.TimingInfo.content)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::video_streaming::SabrContextValue_ContentInfo* temp = _impl_.content_;
  _impl_.content_ = nullptr;
  return temp;
}
inline ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NONNULL SabrContextValue_TimingInfo::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.content_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::SabrContextValue_ContentInfo>(GetArena());
    _impl_.content_ = reinterpret_cast<::video_streaming::SabrContextValue_ContentInfo*>(p);
  }
  return _impl_.content_;
}
inline ::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NONNULL SabrContextValue_TimingInfo::mutable_content()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::video_streaming::SabrContextValue_ContentInfo* _msg = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:video_streaming.SabrContextValue.TimingInfo.content)
  return _msg;
}
inline void SabrContextValue_TimingInfo::set_allocated_content(::video_streaming::SabrContextValue_ContentInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.content_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.content_ = reinterpret_cast<::video_streaming::SabrContextValue_ContentInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.SabrContextValue.TimingInfo.content)
}

// -------------------------------------------------------------------

// SabrContextValue

// optional .video_streaming.SabrContextValue.TimingInfo timing = 1;
inline bool SabrContextValue::has_timing() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.timing_ != nullptr);
  return value;
}
inline void SabrContextValue::clear_timing() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timing_ != nullptr) _impl_.timing_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::video_streaming::SabrContextValue_TimingInfo& SabrContextValue::_internal_timing() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::video_streaming::SabrContextValue_TimingInfo* p = _impl_.timing_;
  return p != nullptr ? *p : reinterpret_cast<const ::video_streaming::SabrContextValue_TimingInfo&>(::video_streaming::_SabrContextValue_TimingInfo_default_instance_);
}
inline const ::video_streaming::SabrContextValue_TimingInfo& SabrContextValue::timing() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.timing)
  return _internal_timing();
}
inline void SabrContextValue::unsafe_arena_set_allocated_timing(
    ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timing_);
  }
  _impl_.timing_ = reinterpret_cast<::video_streaming::SabrContextValue_TimingInfo*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:video_streaming.SabrContextValue.timing)
}
inline ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE SabrContextValue::release_timing() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::video_streaming::SabrContextValue_TimingInfo* released = _impl_.timing_;
  _impl_.timing_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE SabrContextValue::unsafe_arena_release_timing() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.SabrContextValue.timing)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::video_streaming::SabrContextValue_TimingInfo* temp = _impl_.timing_;
  _impl_.timing_ = nullptr;
  return temp;
}
inline ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NONNULL SabrContextValue::_internal_mutable_timing() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timing_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::video_streaming::SabrContextValue_TimingInfo>(GetArena());
    _impl_.timing_ = reinterpret_cast<::video_streaming::SabrContextValue_TimingInfo*>(p);
  }
  return _impl_.timing_;
}
inline ::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NONNULL SabrContextValue::mutable_timing()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::video_streaming::SabrContextValue_TimingInfo* _msg = _internal_mutable_timing();
  // @@protoc_insertion_point(field_mutable:video_streaming.SabrContextValue.timing)
  return _msg;
}
inline void SabrContextValue::set_allocated_timing(::video_streaming::SabrContextValue_TimingInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timing_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.timing_ = reinterpret_cast<::video_streaming::SabrContextValue_TimingInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:video_streaming.SabrContextValue.timing)
}

// optional bytes signature = 2;
inline bool SabrContextValue::has_signature() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void SabrContextValue::clear_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signature_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SabrContextValue::signature() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.signature)
  return _internal_signature();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SabrContextValue::set_signature(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.signature_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextValue.signature)
}
inline ::std::string* PROTOBUF_NONNULL SabrContextValue::mutable_signature()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:video_streaming.SabrContextValue.signature)
  return _s;
}
inline const ::std::string& SabrContextValue::_internal_signature() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signature_.Get();
}
inline void SabrContextValue::_internal_set_signature(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signature_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SabrContextValue::_internal_mutable_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.signature_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SabrContextValue::release_signature() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:video_streaming.SabrContextValue.signature)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.signature_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.signature_.Set("", GetArena());
  }
  return released;
}
inline void SabrContextValue::set_allocated_signature(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.signature_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.signature_.IsDefault()) {
    _impl_.signature_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:video_streaming.SabrContextValue.signature)
}

// optional int32 field5 = 5;
inline bool SabrContextValue::has_field5() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void SabrContextValue::clear_field5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field5_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t SabrContextValue::field5() const {
  // @@protoc_insertion_point(field_get:video_streaming.SabrContextValue.field5)
  return _internal_field5();
}
inline void SabrContextValue::set_field5(::int32_t value) {
  _internal_set_field5(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:video_streaming.SabrContextValue.field5)
}
inline ::int32_t SabrContextValue::_internal_field5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field5_;
}
inline void SabrContextValue::_internal_set_field5(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field5_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::video_streaming::SabrContextUpdate_SabrContextScope> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::video_streaming::SabrContextUpdate_SabrContextScope>() {
  return ::video_streaming::SabrContextUpdate_SabrContextScope_descriptor();
}
template <>
struct is_proto_enum<::video_streaming::SabrContextUpdate_SabrContextWritePolicy> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::video_streaming::SabrContextUpdate_SabrContextWritePolicy>() {
  return ::video_streaming::SabrContextUpdate_SabrContextWritePolicy_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // video_5fstreaming_2fsabr_5fcontext_5fupdate_2eproto_2epb_2eh
