// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: video_streaming/stream_protection_status.proto
// Protobuf C++ Version: 6.33.4

#ifndef video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto_2epb_2eh
#define video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto;
}  // extern "C"
namespace video_streaming {
class StreamProtectionStatus;
struct StreamProtectionStatusDefaultTypeInternal;
extern StreamProtectionStatusDefaultTypeInternal _StreamProtectionStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StreamProtectionStatus_class_data_;
}  // namespace video_streaming
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace video_streaming {

// ===================================================================


// -------------------------------------------------------------------

class StreamProtectionStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:video_streaming.StreamProtectionStatus) */ {
 public:
  inline StreamProtectionStatus() : StreamProtectionStatus(nullptr) {}
  ~StreamProtectionStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StreamProtectionStatus* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StreamProtectionStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StreamProtectionStatus(::google::protobuf::internal::ConstantInitialized);

  inline StreamProtectionStatus(const StreamProtectionStatus& from) : StreamProtectionStatus(nullptr, from) {}
  inline StreamProtectionStatus(StreamProtectionStatus&& from) noexcept
      : StreamProtectionStatus(nullptr, ::std::move(from)) {}
  inline StreamProtectionStatus& operator=(const StreamProtectionStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamProtectionStatus& operator=(StreamProtectionStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamProtectionStatus& default_instance() {
    return *reinterpret_cast<const StreamProtectionStatus*>(
        &_StreamProtectionStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StreamProtectionStatus& a, StreamProtectionStatus& b) { a.Swap(&b); }
  inline void Swap(StreamProtectionStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamProtectionStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamProtectionStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StreamProtectionStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StreamProtectionStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StreamProtectionStatus& from) { StreamProtectionStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StreamProtectionStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "video_streaming.StreamProtectionStatus"; }

  explicit StreamProtectionStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StreamProtectionStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StreamProtectionStatus& from);
  StreamProtectionStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StreamProtectionStatus&& from) noexcept
      : StreamProtectionStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 1,
    kMaxRetriesFieldNumber = 2,
  };
  // optional int32 status = 1;
  bool has_status() const;
  void clear_status() ;
  ::int32_t status() const;
  void set_status(::int32_t value);

  private:
  ::int32_t _internal_status() const;
  void _internal_set_status(::int32_t value);

  public:
  // optional int32 max_retries = 2;
  bool has_max_retries() const;
  void clear_max_retries() ;
  ::int32_t max_retries() const;
  void set_max_retries(::int32_t value);

  private:
  ::int32_t _internal_max_retries() const;
  void _internal_set_max_retries(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:video_streaming.StreamProtectionStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StreamProtectionStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t status_;
    ::int32_t max_retries_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StreamProtectionStatus_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StreamProtectionStatus

// optional int32 status = 1;
inline bool StreamProtectionStatus::has_status() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void StreamProtectionStatus::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t StreamProtectionStatus::status() const {
  // @@protoc_insertion_point(field_get:video_streaming.StreamProtectionStatus.status)
  return _internal_status();
}
inline void StreamProtectionStatus::set_status(::int32_t value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:video_streaming.StreamProtectionStatus.status)
}
inline ::int32_t StreamProtectionStatus::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void StreamProtectionStatus::_internal_set_status(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// optional int32 max_retries = 2;
inline bool StreamProtectionStatus::has_max_retries() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void StreamProtectionStatus::clear_max_retries() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_retries_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t StreamProtectionStatus::max_retries() const {
  // @@protoc_insertion_point(field_get:video_streaming.StreamProtectionStatus.max_retries)
  return _internal_max_retries();
}
inline void StreamProtectionStatus::set_max_retries(::int32_t value) {
  _internal_set_max_retries(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:video_streaming.StreamProtectionStatus.max_retries)
}
inline ::int32_t StreamProtectionStatus::_internal_max_retries() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_retries_;
}
inline void StreamProtectionStatus::_internal_set_max_retries(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_retries_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace video_streaming


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // video_5fstreaming_2fstream_5fprotection_5fstatus_2eproto_2epb_2eh
